### ISSUE TITLE
[BUG] Host overview doesn't show actual available storage from longhorn

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1253]
**Describe the bug**
In the host overview, `Storage size` only shows the size of the initial installation disk. It doesn't show the storage that's actually available to longhorn.

**Expected behavior**
Show the actual amount of schedulable storage from Longhorn

**Environment:**
 - Harvester 0.3.0-preview
 - Baremetal with additional disks

**Comment by yasker** [comment]
@guangbochen can you check if this is included in #576 ?

**Comment by guangbochen** [comment]
should be fixed on the latest UI via https://github.com/harvester/dashboard/pull/107 and both the dashboard and host page should show the correct storage available size.

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head. Validated dashboard storage usage with backend Longhorn dashboard. Fixed.

**Comment by alexdepalex** [comment]
This still exists in v0.3.0-rc1. Is that correct?
![image](https://user-images.githubusercontent.com/713019/135346622-8f80c559-a8eb-415c-b875-cffef43a1f9e.png)
![image](https://user-images.githubusercontent.com/713019/135346661-5c8be8ff-6a4a-4960-90ca-23e2c0a55365.png)

**Comment by yasker** [comment]
@alexdepalex I think what Harvester showing here is the added up remaining space on each node, for every disk on the node. So it won't show `Scheduled/Reserved` there. 

Though, it does look like you have tons of more space than showing in Harvester... Is `858GB` coming from the root disk only?

**Comment by lanfon72** [comment]
CPU/Memory will synced sometimes, but Storage always inconsistent in different pages.(overall/details)
I guess we use different APIs to fetch them or doing some calculation behind?

[hosts]
![image](https://user-images.githubusercontent.com/5169694/135589115-ccd45e3e-8482-4d0b-a869-45b536bab9d9.png)
[hosts.node0]
![image](https://user-images.githubusercontent.com/5169694/135588969-edcbb1f0-5573-44b7-a85c-a534afb648df.png)
[hosts.node1]
![image](https://user-images.githubusercontent.com/5169694/135589253-2e69cdaf-8d25-4be7-82a6-65c8fa62aa67.png)
[hosts.node2]
![image](https://user-images.githubusercontent.com/5169694/135589398-4c1660dc-b3f2-4cc1-8f95-a1d040a5b37c.png)

**Comment by lanfon72** [comment]
and please add a space after `used` as the CPU's column (in details page)... :joy_cat:

**Comment by alexdepalex** [comment]
I guess it depends on what you want to communicate.

In the host overview, it seems like reporting local disk usage makes sense, but the label should be changed to reflect that it's actually about local storage and not any additional disks that are used for Longhorn. As observed by @lanfon72, the host overview does report the size of the local disk, but the amount used isn't accurate.

On the host details view, the total storage size only includes the size of the local (/dev/sda) disk. But used is again off and seems to be calculated by calculating the sum of used storage from all mount points except sda1 and sda2. sda4 which is mounted on `/usr/local` also seems to be included in the calculation.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        14G  2.6G   11G  20% /run/initramfs/cos-state
/dev/loop0      3.2G  1.3G  1.7G  43% /
/dev/sda1        42M  1.1M   38M   3% /oem
/dev/sda4       858G   16G  799G   2% /usr/local
/dev/nvme4n1p1  5.8T   23G  5.5T   1% /var/lib/harvester/extra-disks/8f7cf60254105b321e0fb831f496d396
/dev/nvme5n1p1  5.8T  3.5G  5.5T   1% /var/lib/harvester/extra-disks/a85a28f8c285256f467fe32c6cdab809
/dev/nvme2n1p1  5.8T  4.1G  5.5T   1% /var/lib/harvester/extra-disks/af1d66690d9f9203d3f9242728e81dcd
/dev/nvme0n1p1  5.8T  1.5G  5.5T   1% /var/lib/harvester/extra-disks/c83789082b109d053a39d831664b11f5
/dev/nvme1n1p1  5.8T  2.9G  5.5T   1% /var/lib/harvester/extra-disks/e441e324a2978ec883bc2134fcfe4852
/dev/nvme3n1p1  5.8T   47G  5.5T   1% /var/lib/harvester/extra-disks/fe8282cb7c6af27fbec8f03599182f13
```
![image](https://user-images.githubusercontent.com/713019/135597155-33a00374-efb7-4286-831b-5252a3f81443.png)

On the dashboard view, it looks like the total storage size is just the sum of the local disks from each node but no idea where usage is coming from. But since this overview gives an overall view of the cluster, I guess it would make sense to display the amount of storage available from Longhorn.

**Comment by alexdepalex** [comment]
:)

![image](https://user-images.githubusercontent.com/713019/135616196-a1134e7b-b1a1-4385-85cc-c644e6748bfd.png)

**Comment by yasker** [comment]
@alexdepalex Unfortunately we probably need to punt this to v1.0.0 release to take a closer look into how the calculation was done in the frontend.

**Comment by lanfon72** [comment]
Verified it is synced with Longhorn.
[Harvester's storage status]
![image](https://user-images.githubusercontent.com/5169694/138670136-944a353f-6880-4f7d-9af1-4e553662ffcd.png)

[Longhorn's storage status]
![image](https://user-images.githubusercontent.com/5169694/138670196-83db47a2-b481-416f-8d6d-eb71007fc523.png)

[Node's storage status in console view]
![image](https://user-images.githubusercontent.com/5169694/138670392-1e6267d2-908f-4ebf-979d-615da686eee2.png)


Test Information
----
* Environment: **Bare mental DL360** 3 nodes
* Harvester Version: **master-d05a6cc7-head**
### Verify Steps:
 - Install Harvester
 - Open another tab and navigate to `https://<vip>/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/dashboard` as Longhorn's tab
 - Record storage capacity both in Harvester's Host and Longhorn dashboard (`Used` storage would be similar)
 - Upload Images from Harvester
 - Both of Harvester and Longhorn's storage capacity changed. 
Additional Verify:
 - SSH to Node
 - use `df -h /dev/sd*` to check storage capacity
   (`Used` in **/usr/local** should be similar as Harvester's dashboard shown)
