### ISSUE TITLE
[BUG] rke2-coredns-rke2-coredns-autoscaler timeout

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1428]
**Describe the bug**
I powered on my 3 servers with about 10 seconds of difference between them - the pod _rke2-coredns-rke2-coredns-autoscaler_ timedout. 

`kubectl logs pod/rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-rxn2m -n kube-system
I1014 15:14:45.887005       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E1014 15:14:53.580128       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
E1014 15:15:06.381556       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition`

The UI was not visible so I checked `ip a` on all nodes and the VIP was not assigned.

I had to kill `kubectl delete pod/kube-vip-4vrk5 pod/kube-vip-4wnpc pod/kube-vip-wvrz6 -n harvester-system` the kube-vip pods to regain access to the UI.

**To Reproduce**
Start servers with some time between them, maybe 20 seconds. 

**Expected behavior**
pods should wait longer before a timeout happens and creates a condition that needs repairing.

**Support bundle**
https://drive.google.com/file/d/1-ETrNfaEGfUzrfUrTox1l6hne6HEgGUl/view?usp=sharing

**Environment:**
 - Harvester ISO version: 0.3
 - Underlying Infrastructure: Dell R620

**Comment by guangbochen** [comment]
can't reproduce it with the latest `master-head` ISO, can the QA team help to re-validate again, thanks
```
$ kubectl get pod -n kube-system
NAME                                                    READY   STATUS      RESTARTS   AGE
cloud-controller-manager-gc-test                        1/1     Running     1          4h23m
etcd-gc-test                                            1/1     Running     1          4h24m
helm-install-harvester-nvzng                            0/1     Completed   0          4h24m
helm-install-rancher-monitoring-crd-s8ptk               0/1     Completed   0          4h24m
helm-install-rancher-monitoring-px7s2                   0/1     Completed   3          4h24m
helm-install-rke2-canal-xdpxc                           0/1     Completed   0          4h24m
helm-install-rke2-coredns-qgw9h                         0/1     Completed   0          4h24m
helm-install-rke2-metrics-server-46ckb                  0/1     Completed   0          4h24m
helm-install-rke2-multus-gzs6q                          0/1     Completed   0          4h24m
kube-apiserver-gc-test                                  1/1     Running     1          4h23m
kube-controller-manager-gc-test                         1/1     Running     1          4h23m
kube-multus-ds-l4rfl                                    1/1     Running     1          4h24m
kube-proxy-gc-test                                      1/1     Running     1          4h23m
kube-scheduler-gc-test                                  1/1     Running     1          4h23m
rke2-canal-f9zrf                                        2/2     Running     2          4h24m
rke2-coredns-rke2-coredns-7bb4f446c-nbccd               1/1     Running     1          4h24m
rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-d24r4   1/1     Running     1          4h24m
rke2-metrics-server-5df7d77b5b-ppmxx                    1/1     Running     1          4h23m
snapshot-controller-9f68fdd9-c9z7j                      1/1     Running     1          4h24m
snapshot-controller-9f68fdd9-cgkv6                      1/1     Running     1          4h24m
```

**Comment by TachunLin** [comment]
@guangbochen 
This issue can be reproduced with master-45e25939-head on 3 nodes harvester server. 
Move to implement pipeline for further checking. 

### Test result
Fully shutdown all 3 nodes server. 
Then power on server machine in sequence from node 1 -> node 2 -> node 3 in between more than 20 seconds. 
Only the node 1 is working and get the `Error while getting cluster status: timed out waiting for the condition` error 

Node 0 result 
![image](https://user-images.githubusercontent.com/29251855/143412522-62208d3f-ba7d-46e0-b5a2-1cb78237529b.png)

```
hpd8s7:/home/rancher # kubectl logs -n kube-system rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-wnx95 
I1125 09:01:28.738489       1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E1125 09:01:35.937567       1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
```
Node 2 and node 3 not running, can't retrieve rke2 service status
![image](https://user-images.githubusercontent.com/29251855/143412363-d5e84789-3223-4504-9338-2e792ef37352.png)

![image](https://user-images.githubusercontent.com/29251855/143413094-446c1275-67cc-497a-8aa1-5c100a78ae8a.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine (RackD8 ClusterA) 
* Harvester version: master-45e25939-head

### Verify Steps
1. Press `Momentary press` button on iLo to shutdown server 1, 2 and 3
2. Wait until all server machine completely shutdown 
3. Press `Momentary press` to power on server 1 
4. Wait more than 20 minutes then power on server 2
5. Wait more than 20 minutes then power on server 3
6. SSH to node 1, node2 and node 3
7. Run `kubectl get pods --all-namespaces | grep rke2-coredns` 
8. Run `kubectl logs -n kube-system rke2-coredns-rke2-coredns-autoscaler-7c58bd5b6c-wnx95`

**Comment by guangbochen** [comment]
https://github.com/rancher/rke2/issues/2175#issuecomment-985284770, can be resolved by bumping the RKE2 version to `v1.21.7` of the bare-metal cluster.

**Comment by guangbochen** [comment]
should be resolved by https://github.com/harvester/harvester-installer/pull/184 and move for testing.

**Comment by TachunLin** [comment]
Verified `not fixed` on `master-5d6f3db0-head`. Move to implement pipeline

### Result 
Verified several times on both provo bare machine and local kvm machines. 

After user power on 3 harvester nodes machines with about 20 seconds interval between them.
* User `can't access harvester` dashboard by VIP, can only access node 01 IP. 
* `Unable to access` node 2 and node 3 IP. Please refer to the following details 

####  Test result on Provo data center (3 nodes)

1. Can't access harvester dashboard by VIP (http://10.84.44.181)
2. Can only access node 1 IP, unable to access node 2 and node 3 IP
![image](https://user-images.githubusercontent.com/29251855/145713579-a319b39c-505f-4c53-8f13-ab04d2011a23.png)

3. On node 1, user can't run `kubectl get nodes` or `kubectl get pods` to collect more information. Shows `Error from server (Timeout)`

```
hpd8s7:/home/rancher # kubectl get pods
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
hpd8s7:/home/rancher # kubectl get nodes
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get nodes)
```
4. Console output of each node 
 - node 1
 ![image](https://user-images.githubusercontent.com/29251855/145711773-93565cb5-6205-4bb2-8e23-cd78c848ca3b.png)
 - node 2
 ![image](https://user-images.githubusercontent.com/29251855/145711787-b1a552f0-6eda-49d9-9fe1-10fe8d9febff.png)
 - node 3
 ![image](https://user-images.githubusercontent.com/29251855/145711797-2a3a7752-2940-498c-a782-4cc6b78a85cb.png)
 

####  Test result on local kvm machine (3 nodes)

1. Harvester node 1 and node 2 show `Ready` status, however node 3 is `Not Ready`
![image](https://user-images.githubusercontent.com/29251855/145711859-d28c2dee-e6bc-420f-b5db-ed79ec89c87c.png)
2. Can't access harvester dashboard by VIP (http://192.168.122.69)
3. Can only access node 3 IP, unable to access node 1 and node 2 IP
![image](https://user-images.githubusercontent.com/29251855/145713969-ad3726a3-6335-4445-93df-79e65649a87f.png)
4. Can run `kubectl get pods`, `kubectl get nodes` on node 1, it shows one nodes is not running

![image](https://user-images.githubusercontent.com/29251855/145708928-64269297-bbcd-4a97-a4f2-a64aa16a47cb.png)

![image](https://user-images.githubusercontent.com/29251855/145708909-87566e66-2e40-4809-bfbc-084d354eb94a.png)

5. Run `kubectl logs -n kube-system rke2-coredns-rke2-coredns-autoscaler` shows error
![image](https://user-images.githubusercontent.com/29251855/145709035-2c898853-a8ea-46da-be05-f820fadc609e.png)


### Test Environment

* Harvester version: master-5d6f3db0-head (12/11 after 1.0.0-rc1) 
* Test machine: 
  - 3 nodes harvester cluster on provo bare machines 
  - 3 nodes harvester cluster on local kvm machines

                          
### Harvester network information 

* Provo Bare machines 
  - VIP: 10.84.44.181
  - node1: 10.84.44.114
  - node2: 10.84.44.115
  - node3: 10.84.44.116

* Local kvm machines
  - VIP: 192.168.122.69
  - node1: 192.168.122.168
  - node2: 192.168.122.211
  - node3: 192.168.122.94

### Verification Steps

1. Shutdown node 3 harvester machine, wait 10 seconds
2. Shutdown node 2 harvester machine, wait 10 seconds
3. Shutdown node 1 harvester machine
4. Wait for 15 minutes or more
5. Power on node 1 harvester machine, wait 25 seconds
6. Power on node 2 harvester machine, wait 25 seconds
7. Power on node 3 harvester machine
8. Check 3 nodes harvester can back to work

### Additional Context

1. RKE2 server log for `node 1`  on provo bare machine 
 
  - [rke2-server_provo_node1.log](https://github.com/harvester/harvester/files/7698825/rke2-server_provo_node1.log)

2. RKE2 server log for `node 3` on local kvm machine 

  - [rke2_local_node3.log](https://github.com/harvester/harvester/files/7698826/rke2_local_node3.log)

**Comment by TachunLin** [comment]
Verified **fixed** on master-5d6f3db0-head (bare-metal) and master-3d096946-head (local). Close this issue. 

### Result
After shutdown all nodes, wait 20 minutes then power on harvester nodes in sequence
* Can access dashboard by VIP
* Can access each node IP 
* rke2-coredns pods running correctly

** Since the issue was affect by #1669, we have verified fixed base on the following scenarios

1. Harvester have no virtual network enabled
2. Harvester have `harvester-mgmt` enabled, create any vlan except id `1`

* rke2-coredns pods running correctly
```
harvester-node03-1215:/home/rancher # kubectl get pods --all-namespaces | grep rke2-coredns
kube-system helm-install-rke2-coredns-74nsk 0/1 Completed 0 176m
kube-system rke2-coredns-rke2-coredns-5679c85bbb-5qrmm 1/1 Running 1 175m
kube-system rke2-coredns-rke2-coredns-5679c85bbb-zxpf8 1/1 Running 1 147m
kube-system rke2-coredns-rke2-coredns-autoscaler-6889866896-l42m8 1/1 Running 1 175m
```

### Test Information
* Test Environment: 
  - 3 nodes harvester on Provo bare machine
  - 3 nodes harvester on local kvm machines 
* Harvester version: master-5d6f3db0-head (bare-metal) and master-3d096946-head (local)


### Verify Steps

1. Prepare 3 nodes harvester
2. Enable virtual network with harvester-mgmt
3. create vlan network vlan 806 with id 806
4. create several vm
5. Provision a RKE2 cluster
6. Press 'Momentary Press` button to shutdown node 3
7. Press 'Momentary Press` button to shutdown node 2
8. Press 'Momentary Press` button to shutdown node 1
9. Wait for 20 minutes
10. Press 'Momentary Press` button to power on node 1
11. Press 'Momentary Press` button to power on node 2
12. Press 'Momentary Press` button to power on node 3
13. Wait for startup complete
14. Check node and VIP accessibility

### Additional Context
* Please be noted, even we can access harvester VIP and node IP, there is still the timeout message.  
```
harvester-node03-1215:/home/rancher # kubectl logs -n kube-system rke2-coredns-rke2-coredns-autoscaler-6889866896-l42m8
I1215 13:37:49.962821 1 autoscaler.go:49] Scaling Namespace: kube-system, Target: deployment/rke2-coredns-rke2-coredns
E1215 13:37:59.946832 1 autoscaler_server.go:108] Error while getting cluster status: timed out waiting for the condition
I1215 13:38:26.082453 1 plugin.go:50] Set control mode to linear
I1215 13:38:26.547733 1 linear_controller.go:60] ConfigMap version change (old: new: 705) - rebuilding params
I1215 13:38:26.941335 1 linear_controller.go:61] Params from apiserver:
{
"coresPerReplica": 256,
"nodesPerReplica": 16,
"preventSinglePointFailure": true,
"min": 0,
"max": 0,
"includeUnschedulableNodes": false
}
I1215 13:38:33.863914 1 linear_controller.go:80] Defaulting min replicas count to 1 for linear controller
```
