### ISSUE TITLE
[BUG] Monitoring pod OOM after run a period of time

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1531]
**Describe the bug**
After running the Prometheus pod for a period of time e.g 9 days, the monitoring dashboard is empty due to the Prometheus pod being killed by OOM.

**To Reproduce**
```
ks get pod
NAME                                                     READY   STATUS             RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               2/3     CrashLoopBackOff   8          19m
```

![image](https://user-images.githubusercontent.com/4569037/141071749-28425ab3-be22-476c-a703-41931caacf16.png)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by alexdepalex** [comment]
@guangbochen This doesn't only apply to prometheus, but to the node exporter pods as well. In our case, we had to increase the memory limits 2 or 3 fold. Probably related to our hardware setup which increases the amount of metrics that the exporter reports about.

**Comment by guangbochen** [comment]
Good to know and thanks for the info @alexdepalex, we are considering increasing the default resource value a little bit, but in reality, every user will have a different spec of their environment setup, so it is better to expose those configs and allow them to customize it accordingly.

**Comment by abonillabeeche** [comment]
I'm seeing this in my dmesg on the nodes.

```
[  407.202854] prometheus invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=997
[  407.202857] CPU: 24 PID: 36155 Comm: prometheus Tainted: G               X    5.3.18-59.24-default #1 SLE15-SP3
[  407.202858] Hardware name: Dell Inc. PowerEdge R620/0KCKR5, BIOS 2.8.0 06/26/2019
[  407.202859] Call Trace:
[  407.202867]  dump_stack+0x66/0x8b
[  407.202872]  dump_header+0x4a/0x200
[  407.202873]  oom_kill_process+0xe8/0x130
[  407.202875]  out_of_memory+0x105/0x510
[  407.202879]  mem_cgroup_out_of_memory+0xb5/0xd0
[  407.202881]  try_charge+0x7c0/0x800
[  407.202884]  ? __alloc_pages_nodemask+0x15d/0x320
[  407.202886]  mem_cgroup_try_charge+0x70/0x190
[  407.202888]  mem_cgroup_try_charge_delay+0x1c/0x40
[  407.202890]  wp_page_copy+0xa8/0x4e0
[  407.202893]  do_wp_page+0x8e/0x3b0
[  407.202895]  ? __switch_to_asm+0x40/0x70
[  407.202896]  ? __switch_to_asm+0x34/0x70
[  407.202897]  __handle_mm_fault+0xc98/0x1260
[  407.202898]  ? __switch_to_asm+0x40/0x70
[  407.202900]  handle_mm_fault+0xc4/0x200
[  407.202903]  __do_page_fault+0x2ce/0x500
[  407.202904]  do_page_fault+0x30/0x110
[  407.202906]  page_fault+0x3e/0x50
[  407.202908] RIP: 0033:0x410500
[  407.202910] Code: 48 83 c4 18 c3 48 8b 54 24 30 84 02 83 3d e7 3c 5e 04 00 0f 85 36 02 00 00 48 8b 5c 24 20 48 89 5a 10 48 89 42 18 0f b6 70 09 <40> 88 72 4a 48 8b 70 10 83 3d c1 3c 5e 04 00 0f 85 00 02 00 00 48
[  407.202910] RSP: 002b:000000c061df4d98 EFLAGS: 00010246
[  407.202912] RAX: 000000c061ed3200 RBX: 000000000290cf00 RCX: 000000c0005c3c80
[  407.202913] RDX: 000000c061ee6fc0 RSI: 0000000000000000 RDI: 000000000000000e
[  407.202913] RBP: 000000c061df4da8 R08: 000000000000000c R09: 0000000000000040
[  407.202914] R10: 000000c061ee6fc0 R11: 0000000000000000 R12: 00000000000000ff
[  407.202915] R13: 0000000000000000 R14: 00000000035e37f8 R15: 0000000000000000
[  407.202923] memory: usage 1536000kB, limit 1536000kB, failcnt 17910
[  407.202924] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[  407.202925] kmem: usage 7848kB, limit 9007199254740988kB, failcnt 0
[  407.202925] Memory cgroup stats for /kubepods/burstable/pod2341dff5-2099-460a-ae17-81f7de6b6bc0/81c70eb40211e2ef47f237a996c879bd59911d56467ddafed7cc67056218b5d4:
[  407.202936] anon 1562529792
               file 1343488
               kernel_stack 294912
               slab 868352
               sock 0
               shmem 0
               file_mapped 1351680
               file_dirty 0
               file_writeback 0
               anon_thp 1293942784
               inactive_anon 0
               active_anon 1562382336
               inactive_file 1122304
               active_file 0
               unevictable 0
               slab_reclaimable 147456
               slab_unreclaimable 720896
               pgfault 117975
               pgmajfault 198
               workingset_refault 76296
               workingset_activate 0
               workingset_nodereclaim 0
               pgrefill 196
               pgscan 97340
               pgsteal 76440
               pgactivate 132
               pgdeactivate 196
               pglazyfree 0
               pglazyfreed 0
               thp_fault_alloc 330
               thp_collapse_alloc 0
[  407.202937] Tasks state (memory values in pages):
[  407.202937] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[  407.202940] [  36114]  1000 36114   723213   392550  3805184        0           997 prometheus
[  407.202941] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=81c70eb40211e2ef47f237a996c879bd59911d56467ddafed7cc67056218b5d4,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod2341dff5-2099-460a-ae17-81f7de6b6bc0/81c70eb40211e2ef47f237a996c879bd59911d56467ddafed7cc67056218b5d4,task_memcg=/kubepods/burstable/pod2341dff5-2099-460a-ae17-81f7de6b6bc0/81c70eb40211e2ef47f237a996c879bd59911d56467ddafed7cc67056218b5d4,task=prometheus,pid=36114,uid=1000
[  407.203063] Memory cgroup out of memory: Killed process 36114 (prometheus) total-vm:2892852kB, anon-rss:1525380kB, file-rss:44820kB, shmem-rss:0kB
[  407.214941] oom_reaper: reaped process 36114 (prometheus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[  407.265243] audit: type=1400 audit(1636579222.730:183): apparmor="DENIED" operation="ptrace" profile="cri-containerd.apparmor.d" pid=26310 comm="virtlogd" requested_mask="readby" denied_mask="readby" peer="cri-containerd.apparmor.d"
```

**Comment by weihanglo** [comment]
After investigation, I didn't see any possible bug causing OOM killed. My impression is just the same as [what this answer said](https://stackoverflow.com/a/63549682): It's a normal memory insufficient when Prometheus scraping too much too frequently.

I'll propose to expose `resources.requests` and `resources.limits` on prometheus workload to Harvester setting, for giving user a chance to change them.

**Comment by janeczku** [comment]
This problem is observed in 1.0.0, both prometheus and node-exporter are frequently OOM killed:

```
harvey:/var/log # dmesg |grep oom
[536799.627200] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[536799.647252] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=0f34f3a592b532e492d02810f4724d045a33fc4505097ac87cfff562585ed441,mems_allowed=0,oom_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/0f34f3a592b532e492d02810f4724d045a33fc4505097ac87cfff562585ed441,task_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/0f34f3a592b532e492d02810f4724d045a33fc4505097ac87cfff562585ed441,task=prometheus,pid=58306,uid=1000
[536799.723883] oom_reaper: reaped process 58306 (prometheus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[537309.316685] node_exporter invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=999
[537309.364742]  oom_kill_process+0xe8/0x130
[537309.696271] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[537309.726062] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=3da84fbac77f5d444d772993117745ba5ee56331cb505b1b4ea9993eb1d89570,mems_allowed=0,oom_memcg=/kubepods/burstable/podf174bc37-708e-4970-b4dd-0fa3e03913a5,task_memcg=/kubepods/burstable/podf174bc37-708e-4970-b4dd-0fa3e03913a5/3da84fbac77f5d444d772993117745ba5ee56331cb505b1b4ea9993eb1d89570,task=node_exporter,pid=26682,uid=65534
[537309.782648] oom_reaper: reaped process 26682 (node_exporter), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[537334.711661] prometheus invoked oom-killer: gfp_mask=0x400dc0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), order=0, oom_score_adj=998
[537334.760037]  oom_kill_process+0xe8/0x130
[537335.076461] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[537335.096492] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=7ad6a46fa40e19610cfd3aee4f0aad9e1b3c316da1a87a6c36f61a54dd2dada7,mems_allowed=0,oom_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/7ad6a46fa40e19610cfd3aee4f0aad9e1b3c316da1a87a6c36f61a54dd2dada7,task_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/7ad6a46fa40e19610cfd3aee4f0aad9e1b3c316da1a87a6c36f61a54dd2dada7,task=prometheus,pid=55049,uid=1000
[537335.180079] oom_reaper: reaped process 55049 (prometheus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[537949.685726] prometheus invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=998
[537949.731641]  oom_kill_process+0xe8/0x130
[537950.040524] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[537950.060600] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=95f9518021434a439cc0291dfee2a569e854c12dfc16a6d80985886ad74e3f0f,mems_allowed=0,oom_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/95f9518021434a439cc0291dfee2a569e854c12dfc16a6d80985886ad74e3f0f,task_memcg=/kubepods/burstable/pod9da914c2-d3c3-4b7c-84e0-7adff459e247/95f9518021434a439cc0291dfee2a569e854c12dfc16a6d80985886ad74e3f0f,task=prometheus,pid=65083,uid=1000
[537950.142886] oom_reaper: reaped process 65083 (prometheus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB


NAMESPACE                   NAME                                                          READY   STATUS             RESTARTS   AGE
cattle-fleet-local-system   fleet-agent-78f694664b-4pm82                                  1/1     Running            1          5d2h
cattle-fleet-system         fleet-agent-8fcfb99b6-fgp25                                   1/1     Running            0          27h
cattle-fleet-system         fleet-controller-6666887949-rmmr8                             1/1     Running            0          6d4h
cattle-fleet-system         gitjob-7b97c9c7fd-f8swk                                       1/1     Running            2          5d2h
cattle-monitoring-system    prometheus-rancher-monitoring-prometheus-0                    2/3     CrashLoopBackOff   374        6d5h
cattle-monitoring-system    rancher-monitoring-grafana-7f54b7d8bc-mpwrf                   3/3     Running            0          2d2h
cattle-monitoring-system    rancher-monitoring-kube-state-metrics-744b9448f4-2vs8n        1/1     Running            1          5d2h
cattle-monitoring-system    rancher-monitoring-operator-754bcd8cb4-mtrvq                  1/1     Running            1          5d2h
cattle-monitoring-system    rancher-monitoring-prometheus-adapter-77568b975-ljsbt         1/1     Running            1          5d2h
cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-84chg             1/1     Running            580        6d7h
cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-kw75v             1/1     Running            731        7d3h
cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-r2z2b             1/1     Running            702        7d3h

```

**Comment by yasker** [comment]
The original limit was set to 1.5G, which is not enough for a 6-node cluster (48 core, 512GB per node). We need to figure out a way to maybe increase (or at least prompt user to increase) the memory/cpu limit for the pod.

**Comment by w13915984028** [comment]
The complexity of prometheus deployment and resource patch:

@yasker @guangbochen 

The related Pods deployed:
![image](https://user-images.githubusercontent.com/31133476/152384554-03271e48-0209-4074-8010-4d9dcc161e1c.png)

The complex "deployment" generating path, is there something on top of ManagedChart, is under investigation.  The general rule is that the resource limit patch should be done at the beginning of the chain.

Another point: the change starts from ManagedChart or StatefulSet may be reverted, by helm? also under investigation.

![image](https://user-images.githubusercontent.com/31133476/152386408-60a34a3b-8961-4501-81e2-98c0266c2ab7.png)

**Comment by guangbochen** [comment]
I think there will be two approaches to update the related chart configs, can we please help to verify them accordingly and choose the most feasible one:
- update and persist the monitoring `ManagedChart` CR to the ETCD, this is initially configured via https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L1 as a bootstrap resource.
- [Customizing Packaged Components with HelmChartConfig](https://docs.rke2.io/helm/) since the monitoring chart is using a fixed release name with `fleet-local/rancher-monitoring`.

**Comment by DaiYuzeng** [comment]
@w13915984028 could you please add the doc of the Prometheus configuration on this page? thanks!
https://docs.harvesterhci.io/v1.0/monitoring/monitoring/

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-da3f1778-head` (03/07). Move to implement pipeline. 

### Result

Under default cpu/memory limit in harvester-monitoring setting (No limit)


- While creating the second SLES VM, the ssh connection to management node broken, 
  - The monitoring pod `prometheus-rancher-monitoring-prometheus-0` display `Init:0/1` 
   
  ```
    rancher@harvester-node02-220307:~> sudo -i kubectl get pods -n cattle-monitoring-system
  NAME                                                     READY   STATUS     RESTARTS   AGE
  prometheus-rancher-monitoring-prometheus-0               0/3     Init:0/1   0          26m
  rancher-monitoring-grafana-d9c56d79b-7rqwd               3/3     Running    0          3h10m
  rancher-monitoring-kube-state-metrics-5bc8bb48bd-fbzrj   1/1     Running    0          3h10m
  rancher-monitoring-operator-559767d69b-88fcz             1/1     Running    0          3h10m
  rancher-monitoring-prometheus-adapter-8846d4757-jr2jk    1/1     Running    0          3h10m
  rancher-monitoring-prometheus-node-exporter-6t9c4        1/1     Running    0          171m
  rancher-monitoring-prometheus-node-exporter-c7qg5        1/1     Running    0          98m
  rancher-monitoring-prometheus-node-exporter-jrlc8        1/1     Running    0          3h10m
  ```
  ![image](https://user-images.githubusercontent.com/29251855/157036073-374f34d0-899f-454e-a077-987eb046a7a8.png)

  ![image](https://user-images.githubusercontent.com/29251855/157036491-13042250-3a55-4adf-8344-ef1d7c07c5a9.png)
  
  - The monitoring chart on dashboard crash  
  ![image](https://user-images.githubusercontent.com/29251855/157036259-c65c42bf-dcd1-4213-a127-5a70771fabb7.png)

  - The monitoring chart on VM metric crash 
  ![image](https://user-images.githubusercontent.com/29251855/157036212-183121f1-da04-48cd-adab-a7d0bcba1e11.png)

- In the beginning with no VM created, the monitoring chart memory keep stable in 1000Mi usage
  - The monitoring pod did not oom and crash. 
- Create one ubuntu VM, the monitoring chart memory keep stable in 1200Mi usage
  - The monitoring pod did not oom and crash. 



### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: `master-da3f1778-head` (03/07)

### Verify Steps
1. Create a 3 nodes harvester cluster
2. ssh to management node
4. Run K9s 
5. Run `sudo -i kubectl get pods -n cattle-monitoring-system`
6. Monitor Prometheus chart status on dashboard page
7. Monitor Prometheus chart status on VM metrics page
8. Add Ubuntu focal image
9. Add SLES JeOS image
11. Create the first ubuntu VM
12. Repeat step 4 ~ 7 
13. Create the second SLES VM
14. Repeat step 4 ~ 7
15. Edit harvester-monitoring in settings
16. Add CPU and Memory limit
![image](https://user-images.githubusercontent.com/29251855/157037098-17c116e5-ef25-467a-9c45-2fde7acfe31d.png) 

```
{
  "evaluationInterval": "1m",
  "resources": {
    "limits": {
      "cpu": "1000m",
      "memory": "3000Mi"
    },
    "requests": {
      "cpu": "500m",
      "memory": ""
    }
  },
  "retention": "5d",
  "retentionSize": "50GiB",
  "scrapeInterval": "1m",
  "storageSpec": {
    "volumeClaimTemplate": {
      "spec": {
        "accessModes": [
          "ReadWriteOnce"
        ],
        "resources": {
          "requests": {
            "storage": "50Gi"
          }
        },
        "storageClassName": "longhorn",
        "volumeMode": "Filesystem"
      }
    }
  }
}
```
17. Repeat step 4 ~ 7 


### Support Bundle
[supportbundle_bd0e8b5e-c9d7-4aa7-afb6-e6f803c7d6e2_2022-03-07T12-46-58Z.zip](https://github.com/harvester/harvester/files/8197878/supportbundle_bd0e8b5e-c9d7-4aa7-afb6-e6f803c7d6e2_2022-03-07T12-46-58Z.zip)

**Comment by guangbochen** [comment]
see proper workaround https://github.com/harvester/harvester/issues/1887#issuecomment-1038605654, please check if the similar UI config will work, thanks.

**Comment by w13915984028** [comment]
The "Requested Memory" should keep unchanged (as 750Mi) ,  it is empty now, will lead to 0 memory for the POD. It is the minimum memory to a POD, that is why it stays in "Init" state.

Not sure why this field is empty @TachunLin , intended test input or happened to be empty?

Backend does not add webhook to check those potential abnormal values yet. It is more for the user to have a convenient way to set a higher memory limit for prometheus.

At this moment, we may focus on validate when every config is correct, will the prometheus away from OOM.

![image](https://user-images.githubusercontent.com/31133476/157045473-086c9a3e-9c5f-4992-953d-16fd7a1a7839.png)

**Comment by TachunLin** [comment]
@w13915984028, 
The requested memory and memory limit field are by default empty once after harvester installation complete.
No intended input change until I saw the monitoring pod change to `init state`

![image](https://user-images.githubusercontent.com/29251855/157049055-870b9d07-f638-4159-a259-5a4f4a548879.png)


I noticed that while creating the second VM, my ssh connection to harvester node broken. 

Then I try to modify the requested memory to 1000mi and Memory limit to 3000Mi.
However nothing change to the Prometheus pod to keep in the init state.

**Comment by w13915984028** [comment]
A "static" test with master-head version da3f1778d.


![image](https://user-images.githubusercontent.com/31133476/157073335-78c34616-2bb4-4082-b508-740bc619deb2.png)

`Default value in WebUI`
![image](https://user-images.githubusercontent.com/31133476/157073379-40cdec78-4feb-4304-b2ff-d948e6169bf7.png)

`Default value of the running POD`, there is a long chain of config from ManagedChart to POD, explained here https://github.com/harvester/harvester/issues/1531#issuecomment-1029175655
![image](https://user-images.githubusercontent.com/31133476/157073412-db54cd2d-829d-4307-a1d2-7fcd5d078af4.png)

`Customize value in WebUI`
![image](https://user-images.githubusercontent.com/31133476/157073450-f19aaa80-e9e1-486f-a63d-3bf24ccf22f9.png)


![image](https://user-images.githubusercontent.com/31133476/157073475-c679f19c-7f7b-471f-9c37-94019d191efb.png)

`Values are mapped to POD, and POD is restarted with new resource setting`
![image](https://user-images.githubusercontent.com/31133476/157073522-e555820a-8667-474c-962b-6b4157fcb125.png)

`Set to another value, POD is also restarted with new resource setting`
![image](https://user-images.githubusercontent.com/31133476/157073571-4dce171f-0464-4f21-bb2e-0faeca96f374.png)

![image](https://user-images.githubusercontent.com/31133476/157073686-84bed361-952a-432d-b14c-24618c1a7832.png)

`new resource limit is applied`
![image](https://user-images.githubusercontent.com/31133476/157073711-28832361-319e-406d-ac26-4f1dfc35f2a9.png)


@TachunLin @guangbochen @DaiYuzeng 
To this point, the WebUI config is effective.

**Comment by w13915984028** [comment]
@TachunLin @guangbochen @FrankYang0529 

The failure in @TachunLin test, I am suspecting it may be related to CPU overcommit .

In the test environment, there are 3 nodes` Test Environment: 3 nodes harvester on local kvm machine`  (looks to be 16GB each?) ,  , all of them are management nodes,  @TachunLin  also mentioned `While creating the second SLES VM, the ssh connection to management node broken,`

Quite possilbe: `after second VM is deployed, all of the VMs are running in same node, this management node is running out of memory,`

**Comment by w13915984028** [comment]
@TachunLin as we discussed, please test via:
1. Check if only change resource setting will work, not mixing with VM deployment
2. Test via a 4+node environment,  thus the guest VM will be deployed in the worker node first, then watch the resource usage of harvester-monitoring.  or 3-node/1-node with at least 32GB memory per node.

**Comment by TachunLin** [comment]
### Test Scenario 1: Apply monitoring settings and check monitoring dashboard without VM created

Checked the apply monitoring setting test scenario on 3 nodes harvester cluster on local kvm. 
* Harvester version: master-94a762ab-head (03/11)

### Test Result
1. Can apply monitoring chart settings to Prometheus pod, but need to clarify whether all harvester nodes can be covered by the resource limitation 
2. Monitoring chart keep displaying when no VM created.

* The default monitoring resource limit 
```
 {
  "evaluationInterval": "1m",
  "resources": {
    "requests": {
      "cpu": "500m"
    }
  },
  "retention": "5d",
  "retentionSize": "50GiB",
  "scrapeInterval": "1m",
  "storageSpec": {
    "volumeClaimTemplate": {
      "spec": {
        "accessModes": [
          "ReadWriteOnce"
        ],
        "resources": {
          "requests": {
            "storage": "50Gi"
          }
        },
        "storageClassName": "longhorn",
        "volumeMode": "Filesystem"
      }
    }
  }
}
```


![image](https://user-images.githubusercontent.com/29251855/158096468-1a42701a-2485-445e-ba57-79f7fd80b72c.png)

* Input CPU, Memory limt 

![image](https://user-images.githubusercontent.com/29251855/158097936-5e8fd358-d2eb-449b-9f78-6a6bd65a0e0b.png)

* Monitoring pod will recreated and initialize
```
rancher@harvester-node01-220311:~> sudo -i kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0          33s
rancher-monitoring-grafana-d9c56d79b-b25hc               3/3     Running   0          37m
rancher-monitoring-kube-state-metrics-5bc8bb48bd-qx4hj   1/1     Running   0          37m
rancher-monitoring-operator-559767d69b-7z94t             1/1     Running   0          37m
rancher-monitoring-prometheus-adapter-8846d4757-4hwdw    1/1     Running   0          37m
rancher-monitoring-prometheus-node-exporter-4sf8m        1/1     Running   0          37m
rancher-monitoring-prometheus-node-exporter-qf4sj        1/1     Running   0          21m
rancher-monitoring-prometheus-node-exporter-xrf99        1/1     Running   0          29m
```
* Check the monitoring settings have been applied

```
rancher@harvester-node01-220311:~> sudo -i kubectl get pods -n cattle-monitoring-system prometheus-rancher-monitoring-prometheus-0 -o JSON | grep memory -2
                    "limits": {
                        "cpu": "1",
                        "memory": "3500Mi"
                    },
                    "requests": {
                        "cpu": "500m",
                        "memory": "800Mi"
                    }
                },
--
                    "limits": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    }
                },
--
                    "limits": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "50Mi"
                    }
                },
```

@w13915984028, On 3 nodes harvester cluster, it looks like the monitoring settings on UI only apply to the one of the harvester node, will this have impact while creating resource on other nodes without resource setting applied?

**Comment by TachunLin** [comment]
### Test Scenario 2: Three nodes harvester (tight resources) with 1 VM created

Checked the apply monitoring setting test scenario on 3 nodes harvester cluster on local kvm. 
* Harvester version: master-94a762ab-head (03/11)
* Monitoring settings:
  - CPU limit: 1
  - Requested Memory: 800Mi
  - Memory Limit: 3500Mi 

### Test Result 
1. Check the monitoring dashboard over time, dashboard **`sometime will display empty`**, after refreshing the page for a whie, the dashboard can come back 
![image](https://user-images.githubusercontent.com/29251855/158116920-dfc74d53-728d-4b30-868e-0d9519592f60.png)

2. The resource usage keep in 1000 ~ 1300 MiB
![image](https://user-images.githubusercontent.com/29251855/158117022-1eb07c8f-5447-4812-87cb-1b297dcbe59f.png)

3. The monitoring pod have no crash 
```
rancher@harvester-node01-220311:~> sudo -i kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0          3h50m
rancher-monitoring-grafana-d9c56d79b-b25hc               3/3     Running   0          4h27m
rancher-monitoring-kube-state-metrics-5bc8bb48bd-qx4hj   1/1     Running   0          4h27m
rancher-monitoring-operator-559767d69b-7z94t             1/1     Running   0          4h27m
rancher-monitoring-prometheus-adapter-8846d4757-4hwdw    1/1     Running   0          4h27m
rancher-monitoring-prometheus-node-exporter-4sf8m        1/1     Running   0          4h27m
rancher-monitoring-prometheus-node-exporter-qf4sj        1/1     Running   0          4h10m
rancher-monitoring-prometheus-node-exporter-xrf99        1/1     Running   0          4h19m
```

#### Support Bundle
[supportbundle_e54fcdb3-17f5-42ad-a748-3d51e3afc40a_2022-03-14T06-38-28Z.zip](https://github.com/harvester/harvester/files/8242280/supportbundle_e54fcdb3-17f5-42ad-a748-3d51e3afc40a_2022-03-14T06-38-28Z.zip)

**Comment by TachunLin** [comment]
### Test Scenario 3: Two nodes (sufficient resources) with 3 VM created

Checked the apply monitoring setting test scenario on 2 nodes harvester cluster on local kvm. 
* Harvester version: master-94a762ab-head (03/11)
* Harvester node spec:
  - CPU: 10 core
  - Memory: 25GB
* Monitoring settings:
  - CPU limit: Empty
  - Requested Memory: Empty
  - Memory Limit: Empty

### Test Result 
1. Check the monitoring dashboard over time, dashboard **`sometime will display empty`**, after refreshing the page for a whie, the dashboard can come back 
![image](https://user-images.githubusercontent.com/29251855/158130967-8f27bb9b-b5aa-48b3-aa5e-a7a8b4aff9a0.png)

2. The resource usage keep stable in 500 ~ 600 MiB
![image](https://user-images.githubusercontent.com/29251855/158131065-583bd73c-9422-4077-8eb9-6ee3f49eaf93.png)

3. The monitoring pod have no crash 
  ```
  harvester-node01-220311:~ # kubectl get pods -n cattle-monitoring-system
  NAME                                                     READY   STATUS    RESTARTS   AGE
  prometheus-rancher-monitoring-prometheus-0               3/3     Running   0          5h14m
  rancher-monitoring-grafana-d9c56d79b-f4xqg               3/3     Running   0          5h15m
  rancher-monitoring-kube-state-metrics-5bc8bb48bd-g6cp6   1/1     Running   0          5h15m
  rancher-monitoring-operator-559767d69b-smhcc             1/1     Running   0          5h15m
  rancher-monitoring-prometheus-adapter-8846d4757-k4bsb    1/1     Running   0          5h15m
  rancher-monitoring-prometheus-node-exporter-sqrnh        1/1     Running   0          5h15m
  rancher-monitoring-prometheus-node-exporter-vlcjg        1/1     Running   0          4h39m
  ```

#### Support Bundle
[supportbundle_bd0e8b5e-c9d7-4aa7-afb6-e6f803c7d6e2_2022-03-07T12-46-58Z.zip](https://github.com/harvester/harvester/files/8243000/supportbundle_bd0e8b5e-c9d7-4aa7-afb6-e6f803c7d6e2_2022-03-07T12-46-58Z.zip)

**Comment by TachunLin** [comment]
### Test Scenario 4: Three nodes (sufficient resources) with 8 VM created with `default` monitoring limit settings

Checked the apply monitoring setting test scenario on 3 nodes harvester cluster on **`Provo bare metal machines`**
* Harvester version: master-94a762ab-head (03/11)
* Harvester node spec:
  - CPU: 24 ~ 48 core
  - Memory: 128 GB
* Monitoring settings:
  - CPU limit: 1000m
  - Memory Limit: 2500Mi
  - Requested CPU: 750m
  - Requested Memory: 1750Mi
* Duration: 28 hours
  
  
### Test Result 
1. During 20 hours duration, the **`monitoring dashboard crashed twice `** while the node 3 monitoring chart restart three times
2. If dashboard display empty, after `ctrl+r` refresh page, the monitoring chart can come back  
  ![image](https://user-images.githubusercontent.com/29251855/158296187-2ca0dc0b-5f88-43f0-b6a4-ff4fe2059add.png)
  ![image](https://user-images.githubusercontent.com/29251855/158296217-d6d3cf24-bce1-42ef-84fc-a5ae42125a96.png)

  ```
   rancher@hpd8s7:~> sudo -i kubectl get pods -n cattle-monitoring-system
  NAME                                                     READY   STATUS    RESTARTS        AGE
  prometheus-rancher-monitoring-prometheus-0               3/3     Running   0               28h
  rancher-monitoring-grafana-d9c56d79b-f8cq4               3/3     Running   0               28h
  rancher-monitoring-kube-state-metrics-5bc8bb48bd-b4bfp   1/1     Running   0               28h
  rancher-monitoring-operator-559767d69b-rmzxf             1/1     Running   0               28h
  rancher-monitoring-prometheus-adapter-8846d4757-mr46w    1/1     Running   0               28h
  rancher-monitoring-prometheus-node-exporter-b2xp4        1/1     Running   0               28h
  rancher-monitoring-prometheus-node-exporter-w559r        1/1     Running   4 (5h27m ago)   27h
  rancher-monitoring-prometheus-node-exporter-xhrtm        1/1     Running   0               26h
  ```
3. 8 VM created among node 1 ~ node 3
![image](https://user-images.githubusercontent.com/29251855/158201642-41545db2-18c5-4b63-9861-cdc842e02826.png)
4. The resource usage keep stable in 1000 ~ 1300 MiB no exceed 1500 MiB
![image](https://user-images.githubusercontent.com/29251855/158313723-490b4c64-af73-4748-b042-0063f5503bae.png)
![image](https://user-images.githubusercontent.com/29251855/158390425-3b625b51-8e9b-4513-b346-c861a18c123a.png)


### Support Bundle
[supportbundle_370c2d36-59a7-4865-a33e-598348c1ede9_2022-03-15T06-31-23Z.zip](https://github.com/harvester/harvester/files/8250767/supportbundle_370c2d36-59a7-4865-a33e-598348c1ede9_2022-03-15T06-31-23Z.zip)
[supportbundle_e54fcdb3-17f5-42ad-a748-3d51e3afc40a_2022-03-14T06-38-28Z.zip](https://github.com/harvester/harvester/files/8253519/supportbundle_e54fcdb3-17f5-42ad-a748-3d51e3afc40a_2022-03-14T06-38-28Z.zip)

**Comment by TachunLin** [comment]
### Test Scenario 5: Three nodes (sufficient resources) with 8 VM created *`Have`* monitoring limit settings

#### Status: `Ongoing`

**Comment by TachunLin** [comment]
### Test Result Summary 
  #### According to above test scenarios:

1. Initial monitoring limit value already added to UI 
  ![image](https://user-images.githubusercontent.com/29251855/158385071-2ae0b222-5ba3-4823-969a-9c7046112a99.png)
2. Can update monitoring value in UI and apply monitoring chart settings to Prometheus pod, 
    but it looks like the monitoring resource limitation not applied to all harvester nodes in multi nodes harvester.
3.  With default monitoring value setting, encounter **`sometimes monitoring crash`**  on **three** nodes local kvm machine (6core 16GB, no VM) -> `Test scenario #2`
4.  With default monitoring value setting, encounter **`sometimes monitoring crash`**  on **two** nodes local kvm machine (10 core, 20GB, 4 VMs) -> `Test scenario #3`
5. With default monitoring value setting, encounter **`monitoring crash twice`**  on **three** nodes provo bare machines (24~48core, 128GB, 8 VMs) -> `Test scenario #4`
6. Each time monitoring dashboard crash with empty display, after refresh page (ctrl + r), monitoring can come back 
7. Prometheus pod memory usage remain stable without exceeding 1500MB 
8. Each time when monitoring chart crash, the Prometheus pod did not crash, some pod restarts during long time   

@w13915984028, @guangbochen 
Since the monitoring dashboard and VM metrics still encounter empty display, I would suggest to further check it to improve the stability of this feature. Move it to implement pipeline.

**Comment by w13915984028** [comment]
@TachunLin Thanks for those detailed test, I will check those open points.  cc @guangbochen

**Comment by w13915984028** [comment]
1. About the restart of `prometheus-node-exporter`: **it is caused by OOM,  the memoy limit of "50Mi" is not an reasonable value when many VMs are deployed in one Node**.  But what value could be reasonable?

@guangbochen @TachunLin @yasker 

`prometheus-node-exporter` restarted 4 times
```
 rancher@hpd8s7:~> sudo -i kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS        AGE
..
rancher-monitoring-prometheus-node-exporter-w559r        1/1     Running   4 (5h27m ago)   27h
```

`prometheus-node-exporter` has a very small resource limitation:
e.g. k get pod -n cattle-monitoring-system  rancher-monitoring-prometheus-node-exporter-msgzt -o JSON
![image](https://user-images.githubusercontent.com/31133476/158421911-1311c651-81ab-401d-bd05-342ba68a7c3a.png)
it is also mentioned here
https://github.com/harvester/harvester/issues/1531#issuecomment-1029175655



OOM is checked here in the support bundle:

supportbundle_e54fcdb3-17f5-42ad-a748-3d51e3afc40a_2022-03-14T06-38-28Z/supportbundle_370c2d36-59a7-4865-a33e-598348c1ede9_2022-03-15T13-09-57Z/nodes/harvester-lqxps/logs/kernel.log

```
task=install-cnis.sh  (should also be checked)
harvester-w2hgh/logs/kernel.log:1510:Mar 14 11:00:51 harvester-w2hgh kernel: cp invoked oom-killer: gfp_mask=0x101cca(GFP_HIGHUSER_MOVABLE|__GFP_WRITE), order=0, oom_score_adj=999
harvester-w2hgh/logs/kernel.log:1586:Mar 14 11:00:51 harvester-w2hgh kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=21dc53386378a57ab3a03fce6affd6fb2bba1c1a278309e047e117146e816031,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod0b995851-0ac7-40de-b537-860767e9225c,task_memcg=/kubepods/burstable/pod0b995851-0ac7-40de-b537-860767e9225c/21dc53386378a57ab3a03fce6affd6fb2bba1c1a278309e047e117146e816031,task=install-cnis.sh,pid=3293,uid=0

task=node_exporter
harvester-lqxps/logs/kernel.log:34296:Mar 14 19:06:27 harvester-lqxps kernel: node_exporter invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=999
harvester-lqxps/logs/kernel.log:34361:Mar 14 19:06:27 harvester-lqxps kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=845d964a54a0a3b33310fe5f183e0a447918a8954a45b06d614554ae7831c759,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283,task_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283/845d964a54a0a3b33310fe5f183e0a447918a8954a45b06d614554ae7831c759,task=node_exporter,pid=3553,uid=65534

task=node_exporter
harvester-lqxps/logs/kernel.log:51414:Mar 14 21:54:27 harvester-lqxps kernel: node_exporter invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=999
harvester-lqxps/logs/kernel.log:51479:Mar 14 21:54:27 harvester-lqxps kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=1b1231f9ef766dda1dcc1969590b0c396525ea434211d84982f4e585f2277070,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283,task_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283/1b1231f9ef766dda1dcc1969590b0c396525ea434211d84982f4e585f2277070,task=node_exporter,pid=4602,uid=65534

task=node_exporter
harvester-lqxps/logs/kernel.log:93190:Mar 15 04:45:27 harvester-lqxps kernel: node_exporter invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=999
harvester-lqxps/logs/kernel.log:93255:Mar 15 04:45:27 harvester-lqxps kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=a1d21908075b3171a1849fb12a4b38dce1360037d5289a3329eea984c1abbe79,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283,task_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283/a1d21908075b3171a1849fb12a4b38dce1360037d5289a3329eea984c1abbe79,task=node_exporter,pid=14874,uid=65534

task=node_exporter
harvester-lqxps/logs/kernel.log:110696:Mar 15 07:36:27 harvester-lqxps kernel: node_exporter invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=999
harvester-lqxps/logs/kernel.log:110761:Mar 15 07:36:27 harvester-lqxps kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=5e069e3a493dfd12796844288b3e73a8b0c9525f506b598b562f5b0600af602c,mems_allowed=0-1,oom_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283,task_memcg=/kubepods/burstable/pod54e28436-34f1-4fec-99b2-754260da5283/5e069e3a493dfd12796844288b3e73a8b0c9525f506b598b562f5b0600af602c,task=node_exporter,pid=36740,uid=65534
```

update: `node-exporter` memory usage

POD `rancher-monitoring-prometheus-node-exporter-w559r` (deployed in NODE: `harvester-lqxps`)  is frequently touching the `50Mi `memory limit. It matches the kernel OOM log.
```
hpd8s7:~ # kubectl get pods -n cattle-monitoring-system rancher-monitoring-prometheus-node-exporter-w559r -o JSON  | grep harvester
                                        "harvester-lqxps"
        "nodeName": "harvester-lqxps",

hpd8s7:~ # kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS       AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0              2d1h
..
rancher-monitoring-prometheus-node-exporter-b2xp4        1/1     Running   0              2d1h
rancher-monitoring-prometheus-node-exporter-w559r        1/1     Running   9 (3h6m ago)   2d1h        
```
![image](https://user-images.githubusercontent.com/31133476/158574855-ec09d25d-14da-4fa3-ab64-5fb9828e9806.png)
![image](https://user-images.githubusercontent.com/31133476/158574913-de296957-3ee5-438d-8393-a3763ecac44f.png)
![image](https://user-images.githubusercontent.com/31133476/158574968-eaacfef0-5a5e-41bb-b71a-236cf22768bb.png)

There are 4 VMs deployed in this NODE:
![image](https://user-images.githubusercontent.com/31133476/158576468-950e15f4-ff56-40c5-af2f-d9fc51bb3461.png)

**Comment by w13915984028** [comment]
For **Test Scenario 2**:  https://github.com/harvester/harvester/issues/1531#issuecomment-1066433564

Three nodes harvester (tight resources) with 1 VM created
The monitoring pod have no crash
```
rancher@harvester-node01-220311:~> sudo -i kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0          3h50m
rancher-monitoring-grafana-d9c56d79b-b25hc               3/3     Running   0          4h27m
rancher-monitoring-kube-state-metrics-5bc8bb48bd-qx4hj   1/1     Running   0          4h27m
rancher-monitoring-operator-559767d69b-7z94t             1/1     Running   0          4h27m
rancher-monitoring-prometheus-adapter-8846d4757-4hwdw    1/1     Running   0          4h27m
rancher-monitoring-prometheus-node-exporter-4sf8m        1/1     Running   0          4h27m
rancher-monitoring-prometheus-node-exporter-qf4sj        1/1     Running   0          4h10m
rancher-monitoring-prometheus-node-exporter-xrf99        1/1     Running   0          4h19m
```

**Analysis:**
It is similar to https://github.com/harvester/harvester/issues/2013
The `prometheus-rancher-monitoring-prometheus-0` is re-deployed. its AGE is 3h50m but others are around 4h27m.
Normally `prometheus-0` is deployed in the first node of the cluster when cluster installing, after that more nodes will join the cluster, `prometheus-0` may be re-deployed to other node.   In test scenario 2, this re-deploy happened.

**There is no crash of POD prometheus-0. 
But for a while, the cluster metric is not viewable from WebUI, force refreshing of web page will have chance to get it back, given the new POD prometheus-0 is ready.**

Why `prometheus-rancher-monitoring-prometheus-0` is re-deployed while/after new nodes joining the cluster, is under investigation.
@TachunLin @guangbochen @yasker @rebeccazzzz

**Comment by w13915984028** [comment]
Synced with @TachunLin, a short summary as of 16.03.2021:

**Achieved:**
  1. Resources of `rancher-monitoring (POD monitoring-prometheus-0)` can be configured, monitoring-prometheus-0 has stable memory usage, OOM does not happen on monitoring-prometheus-0.
  
**Open points:**
  1. `prometheus-node-exporter` is restarted frequently
    root cause: default memory limit for prometheus-node-exporter is only 50Mi, is easy to be reached when 4+ VMs are deployed in one NODE
    solution: in discussion with Rancher

  2. `cluster metrics` are not available from time to time, but monitoring-prometheus-0 has no crash
    root cause: monitoring-prometheus-0 is re-deployed to other NODES in cluster installation or cluster rebooting (also refer: https://github.com/harvester/harvester/issues/2013)
    solution: under investigation
    
  3. when `prometheus-node-exporter` is restarted, the `cluster metrics` are also not available, but monitoring-prometheus-0 has no crash
    root cause: unknown, under investigation ( @TachunLin encountered, I did not reproduce yet)
    solution:
    
  cc @guangbochen @rebeccazzzz @yasker

**Comment by w13915984028** [comment]
@guangbochen 

The `networking` part of `node-exporter`, may be related to VM numbers.  (to be confirmed)

![image](https://user-images.githubusercontent.com/31133476/159256907-6cc21d9c-658c-4ced-a534-3e90ba4d5f95.png)

**Comment by FrankYang0529** [comment]
Validate [Test Scenario 2](https://github.com/harvester/harvester/issues/1531#issuecomment-1066433564) with Harvester master-9664bf67-head. Following test cases can pass.

**Case1: prometheus-node-exporter pods don't crash**
1. Create a 3-node cluster.
2. Create a VM.
3. Open the VM Metrics page and stay on the page for hours.
4. We can see metrics on the page and the page doesn't crash.
5. Pods in `rancher-monitoring-prometheus-node-exporter` DaemonSet don't crash.

**Case2: Update prometheus-node-exporter in rancher-monitoring ManagedChart**
1. Update `prometheus-node-exporter.resources.limits.memory` from `180Mi` to `200Mi`.
2. Check whether `resources.limits.memory` in `rancher-monitoring-prometheus-node-exporter` DaemonSet is `200Mi`.

**Comment by guangbochen** [comment]
can we please check if we can close this issue, there is an exceptional case of `unstable deployment of POD prometheus-0` which is tracked via #2013, thanks?

**Comment by w13915984028** [comment]
Agree with @guangbochen, I prefer to close this issue, the original scope is fixed by 

https://github.com/harvester/dashboard/pull/247
https://github.com/harvester/dashboard/pull/263
https://github.com/harvester/harvester-installer/pull/240
https://github.com/harvester/harvester-installer/pull/250 

the OOM of prometheus-0 and node-exporter is no longer in v1.0.1.

In the meanwhile, another new issue was found and tracked in #2013, it will be fixed in v1.0.2.

@TachunLin @FrankYang0529  your idea? Thanks.

**Comment by TachunLin** [comment]
@w13915984028, @guangbochen
Double confirm this issue on harvester `v1.0.1`, still encounter the monitoring chart empty sympton.
Please check and advice whether we should look deep into this issue.

* During the 4 hours period checking, the monitoring chart still encounter empty several times like the following
![image](https://user-images.githubusercontent.com/29251855/163187809-99b414b6-c6fd-442b-abdf-b5149b182b8d.png)

* The Prometheus pod running as expected, the node-exporter pod did not restart
```
rancher@harvester-node-2:~> sudo -i kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0          4h52m
rancher-monitoring-grafana-d9c56d79b-kcjwh               3/3     Running   0          4h52m
rancher-monitoring-kube-state-metrics-5bc8bb48bd-49l2q   1/1     Running   0          4h52m
rancher-monitoring-operator-559767d69b-sq58h             1/1     Running   0          4h52m
rancher-monitoring-prometheus-adapter-8846d4757-d65xh    1/1     Running   0          4h52m
rancher-monitoring-prometheus-node-exporter-d7xsn        1/1     Running   0          4h52m
rancher-monitoring-prometheus-node-exporter-lxrrv        1/1     Running   0          4h24m
rancher-monitoring-prometheus-node-exporter-pspnn        1/1     Running   0          4h39m
```
* Use the default monitoring setting 
```
 {
  "evaluationInterval": "1m",
  "resources": {
    "limits": {
      "cpu": "1000m",
      "memory": "2500Mi"
    },
    "requests": {
      "cpu": "750m",
      "memory": "1750Mi"
    }
  },
  "retention": "5d",
  "retentionSize": "50GiB",
  "scrapeInterval": "1m",
  "storageSpec": {
    "volumeClaimTemplate": {
      "spec": {
        "accessModes": [
          "ReadWriteOnce"
        ],
        "resources": {
          "requests": {
            "storage": "50Gi"
          }
        },
        "storageClassName": "longhorn",
        "volumeMode": "Filesystem"
      }
    }
  }
}
```

### Support Bundle
[supportbundle_8c4a93cf-b167-4ef8-b4d4-acb17de158fe_2022-04-13T13-15-14Z.zip](https://github.com/harvester/harvester/files/8481773/supportbundle_8c4a93cf-b167-4ef8-b4d4-acb17de158fe_2022-04-13T13-15-14Z.zip)

**Comment by w13915984028** [comment]
Update:
From nginx log of support bundle by @TachunLin , there are no http GET exceptions, back end PODs have no errors.

From a happend local debug, it seems the front end scripts are stucking:

`Click "Reload"`
![image](https://user-images.githubusercontent.com/31133476/163280801-e0749d6b-602c-4947-a386-d43f541ebac4.png)

`A couple of HTTP GET are triggered and all are successful, but the front end is still in "Loading".`
![image](https://user-images.githubusercontent.com/31133476/163280816-7f3b8c4e-33a6-43a2-9d12-50160ab526c2.png)


Asking help from front end experts.

**Comment by TachunLin** [comment]
According to the investigation https://github.com/harvester/harvester/issues/1531#issuecomment-1098545912. 
The Prometheus monitoring pod is running without crash and the monitoring-node-exporter did not encounter restarts as well.

When abnormal,  front end is stucking in "Loading...", but there are no ongoing/failure http requests.
To narrow down the scope, we will close this issue and continue tracking in #2150
