### ISSUE TITLE
[BUG] Cannot use local AD time server for NTP time source

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#1699]
**Describe the bug**
Cannot use local AD time server for NTP time source

**To Reproduce**
During initial installation, in menu: 
`Configure NTP Servers`

Enter local AD server as NTP server, local IP `192.168.1.2` for example. 

Error message:

```
Failed to reach NTP servers: fail to validate NTP servers: [192.168.1.2], err: read udp 192.168.1.153:35475->192.168.1.2:123: i/o timeout. Press Enter to continue or change the input to revalidate.
```

**Expected behavior**

`Configure NTP Servers` option to be compatible with AD. (Is it a udp issue?)

Edit: I should note, the firewall on the AD server is currently OFF.

**Support bundle**
I don't think this would help, as I had to enter the parent NTP server (the one the AD master clock syncs with) to continue installation, so I imagine there'd be no record of my configuration error once I get the cluster up and running

**Environment:**
 - Harvester ISO version: 1.0-rc2 on 2021-12-17
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vSphere 7.0U2 on 2 E5-v3/v4 whiteboxes.

**Additional context**
First time trying harvester or rancher products (besides a K3os ISO for like 5 minutes). Extremely kube-green, go easy on me.

**Comment by sazhufa** [comment]
I think this relate to the network time protocol (NTP) version.

- [Windows Time Service provides NTPv3](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/how-the-windows-time-service-works#ntp-time-provider)
- chronyd provides NTPv4&v3
- ntpd provides NTPv5&v4 (or v3 ?)

I deloyed a chronyd 4.2 shipped by openSUSE-TW, but chronyd does not response the NTPv5 request, and the Harvester installer said NTP server timeout.

I redeloyed a ntp 4.2.8 at same OS, see that ntpd reponse NTPv5 request immediately and Harvester installer pass the NTP server check step shortly.

Harvester installer may be change its NTP version for increase the compatibility in customer's environment.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-c5bfa702-head**

### Verify Steps:
1. Install Harvester with the Console UI
2. Input `time.windows.com` as the NTP Server
3. NTP Validation should not display any errors
4. When Harvester Installed, Login to console
5. Execute `sudo timedatectl timesync-status`
6. The NTP Server `time.windows.com` should displayed

**Comment by averyfreeman** [comment]
Trying to set up another node, and now realizing I still get this error harvester 1.01 iso. Same error (first message) Both with time.windows.com and local AD.  However, it looks like I can hit enter again to move on in the installation process.

**Comment by lanfon72** [comment]
@averyfreeman this issue will be fixed in `v1.0.2`.
And as NTP server can not be updated after installation, you probably need to re-install whole cluster.

If you still encounter this bug after `v1.0.2`, feel free to re-open it, thanks. :smiley:

**Comment by FrankYang0529** [comment]
Hi @averyfreeman, this was a bug in harvester installer, but it's been fixed. Before v1.0.2 is released, you can try it with [master-head ISO](https://releases.rancher.com/harvester/master/harvester-master-amd64.iso). For your current cluster, you can use a command `timedatectl show-timesync` to see whether the system use your local AD. Also, you can use `timedatectl status` to see the time sync status.
