### ISSUE TITLE
[BUG] Non-exhaustive type checks causing failed schema inspection

### ISSUE THREAD

**Issue by joshmeranda** [harvester/harvester#1919]
When running harvester with binary built from compiling source at f303b27e it fails with an error:

`FATA[0000] failed to create harvester server: failed inspecting type v1beta1.VirtualMachineTemplateVersion, field spec: failed inspecting type v1beta1.VirtualMachineTemplateVersionSpec, field vm: failed inspecting type v1beta1.VirtualMachineSourceSpec, field spec: failed inspecting type v1.VirtualMachineSpec, field template: failed inspecting type v1.VirtualMachineInstanceTemplateSpec, field spec: failed inspecting type v1.VirtualMachineInstanceSpec, field domain: failed inspecting type v1.DomainSpec, field devices: failed inspecting type v1.Devices, field disks: failed inspecting type v1.Disk, field bootOrder: unknown type kind uint`

#### Expected
 - Harvester should startup normally

#### Observed
 - Harvester fails with the error above

#### To reproduce
```
>>> export KUBECONFIG="$HOME/.kube/config" NAMESPACE="harvester-system" RANCHER_EMBEDDED="true" HCI_MODE="true"
>>> go build -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn -X github.com/harvester/harvester/vendor/google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn"
>>> ./harvester
```

After digging into the source it looks like this is caused by type checks in [Wrangler](https://github.com/rancher/wrangler)'s reflection type checks being non-exhaustive and omitting the `Uint` go type at [reflection.go#271](https://github.com/rancher/wrangler/blob/master/pkg/schemas/reflection.go#L271) and [reflection.go#467](https://github.com/rancher/wrangler/blob/master/pkg/schemas/reflection.go#L467) which cause the `unknown type kind uint` error thrown as [reflection.go#524](https://github.com/rancher/wrangler/blob/master/pkg/schemas/reflection.go#L524).

**Comment by joshmeranda** [comment]
Here is a code sample  with an example of the issue:

```go 
import (
"fmt"
"github.com/rancher/wrangler/pkg/schemas/openapi"
)

type sample struct {
	BootOrder uint
}

func main() {
	json, err := openapi.ToOpenAPIFromStruct(sample{})
	if err != nil {
		fmt.Printf("Error: %s\n", err)
	}

	_ = json

}
```

This code will output:

```
Error: failed inspecting type main.sample, field bootOrder: unknown type kind uint
```

**Comment by joshmeranda** [comment]
~Waiting for wrangler [MR 198](https://github.com/rancher/wrangler/pull/198) before updating vendor dependency.~

**Comment by joshmeranda** [comment]
Resolved in PR [198](https://github.com/rancher/wrangler/pull/198)

**Comment by voarsh2** [comment]
I'm still getting this error when I download from master branch....

**Comment by joshmeranda** [comment]
Looks like we never updated the harvester dependency, I put up a PR that will fix this.

**Comment by bk201** [comment]
Move to 1.2.0 to check if we still have this issue.

**Comment by WebberHuang1118** [comment]
This issue has been fixed on [Harvester master](https://github.com/harvester/harvester)

**Root Cause**
During [apply CRD VirtualMachineTemplateVersion](https://github.com/harvester/harvester/blob/365036c52ce3423eb7736a33c4f3c7b08a28035f/pkg/data/crd.go#L46), the nested field [BootOrder](https://github.com/kubevirt/api/blob/11032ecb331f9199436980e8a9451586258ad75a/core/v1/schema.go#L554) is not well handled in [Wangler's type check](https://github.com/rancher/wrangler/blob/5a387e13e8d51e3340d9e5012a1951f0cca5fc90/pkg/schemas/reflection.go#L271),  and it [leads to error](https://github.com/rancher/wrangler/blob/5a387e13e8d51e3340d9e5012a1951f0cca5fc90/pkg/schemas/reflection.go#L524)

**Reproduce update**

- Set up Harvester with the latest master build (tested with 2023/04/28 build)
- Delete VirtualMachineTemplateVersion CR and CRD
- Running Harvester binary compiled from https://github.com/harvester/harvester/commit/f303b27ef7479f5727a1d6674b2d543f307575d0
  - $ git clone https://github.com/harvester/harvester.git
  - Reset to commit https://github.com/harvester/harvester/commit/f303b27ef7479f5727a1d6674b2d543f307575d0
    - $ git reset --hard  f303b27ef7479f5727a1d6674b2d543f307575d0
  - $ make build
  - $ export KUBECONFIG="$HOME/.kube/config" NAMESPACE="harvester-system" RANCHER_EMBEDDED="true" HCI_MODE="true"
  - $ ./bin/harvester
  - Error message mentioned in https://github.com/harvester/harvester/issues/1919#issue-1138869654 occurs
 
**Solution**
This has been solved in Wranger from PR [198](https://github.com/rancher/wrangler/pull/198) since [v1.0.0](https://github.com/rancher/wrangler/tree/v1.0.0), and Harvester already bumped Wrangler version to [v1.1.0](https://github.com/harvester/harvester/blob/365036c52ce3423eb7736a33c4f3c7b08a28035f/go.mod#L95)

**Verification**
Running Harvester binary compiled from the latest master, and following the same reproduce steps. We could found there is no error similar to https://github.com/harvester/harvester/issues/1919#issue-1138869654
