### ISSUE TITLE
[BUG] When Harvester deletes an uploading image, the corresponding temp file is not deleted

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#1947]
**Describe the bug**

`When Harvester deletes an ongoing uploading image, the corresponding temp file is left uncleared. In worst case, it may occupy all the disk space.`

**To Reproduce**

detailed steps are also described in:
https://github.com/longhorn/longhorn/issues/3682

1. Create image (uploading from local file) in Harvester
![image](https://user-images.githubusercontent.com/31133476/156240313-8e8670f0-659a-424f-8877-38f9b2fb2509.png)

2. An uploading image is created, a temp file is created 
![image](https://user-images.githubusercontent.com/31133476/156240415-44bce22b-a2ed-4fc7-8e6a-8d42c2a269b0.png)

3.Delete the uploading image
![image](https://user-images.githubusercontent.com/31133476/156240454-c6d8f6ce-b1b4-4556-8ef7-c15e156cf8a6.png)

4. The temp file is left uncleared, the related LH uploading POD has already gone.
![image](https://user-images.githubusercontent.com/31133476/156239892-c7004793-0367-4317-901e-4a4343d4fc16.png)

**Expected behavior**

Temp file should be cleared asap and correctly.

**Support bundle**

**Environment:**

 - Harvester ISO version:  Harvester v1.0.0 master-head with longhorn embedded.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

When LH solves 3682, Harvester needs syncing up and validation.

https://github.com/longhorn/longhorn/issues/3682

**Comment by w13915984028** [comment]
LH has fixed this issue in 
https://github.com/longhorn/longhorn/issues/3682

Harvester needs to verify when related LH version is bumped.

**Comment by bk201** [comment]
To validate after bumping Longhorn v1.4.2.

**Comment by bk201** [comment]
@WebberHuang1118 Please help verify if it's fixed in LH 1.4.2 too. Thanks!

**Comment by WebberHuang1118** [comment]
Issue still found in a different situation

**Environment:**
- Harvester version: master (2023/06/01)

**Reproduce steps:**
- Create image (uploading from local file) in Harvester
- Once a temp file is created in Harvester (at /var/lib/harvester/defaultdisk/tmp) ![bi_temp_file](https://github.com/harvester/harvester/assets/19387129/db790af1-224b-4071-91c8-ecb2bbed6f01)
- Delete the uploading image

**Result:**
- a backing image is left uncleared (at /var/lib/harvester/defaultdisk/backing-images)
![bi_backingimagefile](https://github.com/harvester/harvester/assets/19387129/15bba0d1-6261-4212-a2d4-317fbbf572a1)
- Although CR virtualmachineimage is deleted, CR backingimage is stuck in deletion process![bi_stuck1](https://github.com/harvester/harvester/assets/19387129/2cd78c53-9483-49fb-9433-5060f357706e)
![bi_stuck2](https://github.com/harvester/harvester/assets/19387129/be0145ac-5bbc-4ce4-9f83-a821fe7ffa63)
- longhorm manager kept looping with certain messages ![bi_stuck3](https://github.com/harvester/harvester/assets/19387129/fbe1487d-e080-48f8-adbc-3592a5fd162c)

**Expected Behavior:**
- Virtual Machine Image should be deleted with related resources, including backingimage, backingimagedatasoure, and backingimagemanager
- No temp file or backing image file left

**Comment by WebberHuang1118** [comment]
**Analysis:**
As backingimage is deleted during the uploading process, [it keeps in deleting status until backingimagedatasource reaches "failed-and-cleanup" state](https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/controller/backing_image_controller.go#L215rl), which indicates the orphan temp file is cleared. It depends on two operations to meet the condition:
1. backingimagedatasource controller [set its' state to "failed"](https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/controller/backing_image_manager_controller.go#L683) from propagation deletion
2. As backingimagemanger controller finds backingimagedatasource in "failed" state, [it deleted orphan tmp and changes backingimagedatasource's state to "failed-and-cleanup" ](https://github.com/longhorn/longhorn-manager/blob/6856fd35ee1739f517b78be9e1c6df38171be458/controller/backing_image_manager_controller.go#L683)

Because Harvester doesn't delete backingimage with foreground propagation, it can't utilize Longhorn's design pattern, and make backingimage stuck in deletion

**Fix Plan**
Virtualimage controller should delete backingimage with "foreground progagation"

**Comment by WebberHuang1118** [comment]
Testing plan updated at https://github.com/harvester/harvester/issues/1947#issuecomment-1552811050

**Comment by irishgordo** [comment]
Thanks for the fix @w13915984028  - this looks good :smile:  :+1: 

Tested on:
Harvester Version: v1.2-f4968e49-head 

This looks good, I'll go ahead and close this out


https://github.com/harvester/harvester/assets/5370752/e5092af1-367d-4ae6-b700-2d2b168da5e2
