### ISSUE TITLE
[BUG] Harvester should be able to create an HA cluster with three nodes

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#2194]
**Is your feature request related to a problem? Please describe.**
To quote the documentation <https://docs.harvesterhci.io/v1.0/host/host/>

    Harvester is built on top of Kubernetes and uses etcd as its database,
    the maximum node fault toleration is one when there are three management nodes.

and yet in the same documentation 

    The first node always defaults to be a management node of the cluster.
    When there are more than three nodes, the two other nodes that first joined
    are automatically promoted to management nodes to form a HA cluster.

It should be possible to create an HA cluster with exactly three nodes - having more than three nodes should not be a requirement.

**Describe the solution you'd like**
- I would like to be able to create an HA cluster with exactly three nodes.
- I would like to promote nodes 2 and 3 to being management nodes.
- Whether this is automatic or manual, I do not mind.

**Additional context**
This was discussed in Slack: https://rancher-users.slack.com/archives/C01GKHKAG0K/p1650197492586649

**Comment by abonillabeeche** [comment]
Mark - can you elaborate on your request? When deploying a cluster with 3 nodes, it will be HA by default and certainly will tolerate a node failure. The "promotion" takes place automatically when additional management nodes are required and made available. After 3 management nodes are in place, additional nodes would be considered workers.

**Comment by himslm01** [comment]
I have a 3 node Harvester v1.0.0 cluster which has is a master and two workers.
```
$ kubectl get nodes
NAME           STATUS   ROLES                       AGE   VERSION
harvester001   Ready    <none>                      8d    v1.21.7+rke2r1
harvester002   Ready    <none>                      71d   v1.21.7+rke2r1
harvester003   Ready    control-plane,etcd,master   93d   v1.21.7+rke2r1
```
The documentation on the page I quoted has said "more than 3 nodes" from the first commit: https://github.com/harvester/docs/blob/41c944c57509bc10e185ce8c87ae107b34a361f6/docs/host/host.md

**Comment by bk201** [comment]
@himslm01 Could you provide a support bundle? All nodes should become management roles.

BTW, did you delete nodes and rejoin them? From the AGE and host naming, it looks like the first-created one is harvester003, then harvester002, and harvester001.

**Comment by himslm01** [comment]
[supportbundle_5bb44244-434e-4530-ad35-35c4ef1ff661_2022-04-26T07-12-31Z.zip](https://github.com/harvester/harvester/files/8560716/supportbundle_5bb44244-434e-4530-ad35-35c4ef1ff661_2022-04-26T07-12-31Z.zip)

**Comment by himslm01** [comment]
Yes, in this cluster node harvester003 was the first member, then harvester002 then harvester001.
The background to that:
- node harvester001 was first built as v0.2.0 and had some workloads running
- node harvester002 was first built as v0.3.0 but was really only used for testing and demonstrating bugs
- node harvester003 was built as a v1.0.0 and found to be successful and stable
- node harvester002 was trashed and re-built as v1.0.0 joining the harvester003 cluster
- node harvester001 had the workloads moved/rebuilt into the harvester003 cluster, then trashed and re-built as v1.0.0 joining the harvester003 cluster

**Comment by abonillabeeche** [comment]
I think this might be a bug from old code and cannot be reproduced. I just installed both a 1.0 and a 1.0.1 cluster and the expected behavior of 3 mgmt/worker nodes was deployed. You are hitting a 0.2 but.

**Comment by himslm01** [comment]
I don't understand how I can be hitting a v0.2 bug when the cluster is installed from the Harvester ISO for v1.0.0 downloaded on 22nd Jan 2022.

**Comment by bk201** [comment]
@himslm01 From the support bundle I can confirm `harvester002` node is being promoted to the server node. But somehow a rancher plan on that node can't be applied. Because of an issue in v1.0.0, node logs are not included in the bundle. Could you navigate to node `harvester002` and provide output of:
- `sudo systemctl status rancher-system-agent`
- `sudo journalctl -u rancher-system-agent`

This could help me debug, Thanks a lot.

**Comment by himslm01** [comment]
Thank you @bk201 
The output of those two commands is in the attached tar.
[bk202_20220504.tar.gz](https://github.com/harvester/harvester/files/8627319/bk202_20220504.tar.gz)

**Comment by bk201** [comment]
After investigating the support bundle and with the user's help to provide some info, we found the rancher-system-agent can not execute plans on node `harvester002`. And this might be related to the certificate changes:

Restarting rancher-system-agent node:
```
May 06 07:36:00 harvester002 systemd[1]: Stopped Rancher System Agent.
May 06 07:36:00 harvester002 systemd[1]: Started Rancher System Agent.
May 06 07:36:00 harvester002 rancher-system-agent[22137]: time="2022-05-06T07:36:00Z" level=info msg="Rancher System Agent version v0.1.1 (e54e52e) is starting"
May 06 07:36:00 harvester002 rancher-system-agent[22137]: time="2022-05-06T07:36:00Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
May 06 07:36:00 harvester002 rancher-system-agent[22137]: time="2022-05-06T07:36:00Z" level=debug msg="Instantiated new image utility with imagesDir: /var/lib/rancher/agent/images, imageCredentialProviderConfig: /var/lib/rancher/credentia>
May 06 07:36:00 harvester002 rancher-system-agent[22137]: time="2022-05-06T07:36:00Z" level=info msg="Starting remote watch of plans"
May 06 07:36:00 harvester002 rancher-system-agent[22137]: panic: error while connecting to Kubernetes cluster: Get "https://10.64.0.19/version": x509: cannot validate certificate for 10.64.0.19 because it doesn't contain any IP SANs
May 06 07:36:00 harvester002 rancher-system-agent[22137]: goroutine 34 [running]:
May 06 07:36:00 harvester002 rancher-system-agent[22137]: github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc0000bc180, 0x1759280, 0xc00040ee00)
May 06 07:36:00 harvester002 rancher-system-agent[22137]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:96 +0xc74
May 06 07:36:00 harvester002 rancher-system-agent[22137]: created by github.com/rancher/system-agent/pkg/k8splan.Watch
May 06 07:36:00 harvester002 rancher-system-agent[22137]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:57 +0xbe
May 06 07:36:00 harvester002 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 06 07:36:00 harvester002 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
May 06 07:36:05 harvester002 systemd[1]: rancher-system-agent.service: Scheduled restart job, restart counter is at 1.
May 06 07:36:05 harvester002 systemd[1]: Stopped Rancher System Agent.

```

**Comment by bk201** [comment]
@himslm01 By any chance the `server-url` Rancher setting is changed to `http://10.64.0.19` and then to `https://harvester-cluster.lan.lxiv.uk`? This might be the reason the agent can't use the internal URL to communicate with the cluster.

For a temporary workaround, you can try log in to `harvester002` node.
- Backup `/var/lib/rancher/agent/rancher2_connection_info.json`
- Get Rancher internal IP: `kubectl get services rancher -n cattle-system`, the value of `CLUSTER-IP`.
- Edit `/var/lib/rancher/agent/rancher2_connection_info.json` and replace `server: https://10.64.0.19\n` with `https://<Rancher internal IP>\n`.
- `systemctl restart rancher-system-agent`

**Comment by himslm01** [comment]
It is distinctly possible that when I built the first node in this cluster I was using an IP address as the `Management address` in the installer, then later I created a DNS entry and changed the `server-url` configuration setting to the DNS entry.

I had assumed / hoped that all the places which used the `server-url` would have been updated when I changed the setting :-)

Between Zoom calls I'll make the work-around change and see what happens.

**Comment by himslm01** [comment]
@bk201 I decided to be slightly adventurous and did something *slightly* different to your advice.

Instead of getting the Rancher internal IP and replacing it in `/var/lib/rancher/agent/rancher2_connection_info.json` on one host I decided to make sure all three nodes had the `server-uri` set to the FQDN DNS entry value `harvester-cluster.lan.lxiv.uk`.

After editing `/var/lib/rancher/agent/rancher2_connection_info.json`, the moment (or soon after) I did `systemctl restart rancher-system-agent` on the two nodes which were not `control-plane,etcd,master` they got those roles.

I also see from the logs that the Rancher system agent is not in a crash-loop any more.

`journalctl -u rancher-system-agent -S '2022-05-09 10:13:31'|less`

```
May 09 10:13:31 harvester002 systemd[1]: rancher-system-agent.service: Scheduled restart job, restart counter is at 51294.
May 09 10:13:31 harvester002 systemd[1]: Stopped Rancher System Agent.
May 09 10:13:31 harvester002 systemd[1]: Started Rancher System Agent.
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Rancher System Agent version v0.1.1 (e54e52e) is starting"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Instantiated new image utility with imagesDir: /var/lib/rancher/agent/images, imageCredentialProviderConfig: /var/lib/rancher/credentialprovider/config.yaml, imageCredentialProvide
rBinDir: /var/lib/rancher/credentialprovider/bin, agentRegistriesFile: /etc/rancher/agent/registries.yaml"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Starting remote watch of plans"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Initial connection to Kubernetes cluster failed with error Get \"https://harvester-cluster.lan.lxiv.uk/version\": x509: certificate signed by unknown authority, removing CA data and
 trying again"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Starting /v1, Kind=Secret controller"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="[K8s] Processing secret custom-6afa908c52d8-machine-plan in namespace fleet-local at generation 0 with resource version 134167193"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="[K8s] Calculated checksum to be dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="[K8s] Remote plan had an applied checksum value of 2325bdd9b3fb5f778d06860a2bfff974ab20a4c4a254ce5989e3168ed9a17260"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="[K8s] Calling Applyinator to apply the plan."
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Applying plan with checksum dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Writing applied calculated plan contents to historical plan directory /var/lib/rancher/agent/applied"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="reconciling file permissions for /var/lib/rancher/agent/applied/20220509-101331 to 0:0 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Writing file /etc/rancher/rke2/config.yaml.d/50-rancher.yaml"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="requested file permission for /etc/rancher/rke2/config.yaml.d/50-rancher.yaml was , defaulting to 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="reconciling file permissions for /etc/rancher/rke2/config.yaml.d/50-rancher.yaml to 0:0 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Writing file /var/lib/rancher/rke2/server/manifests/rancher/cluster-agent.yaml"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="requested file permission for /var/lib/rancher/rke2/server/manifests/rancher/cluster-agent.yaml was , defaulting to 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="reconciling file permissions for /var/lib/rancher/rke2/server/manifests/rancher/cluster-agent.yaml to 0:0 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Writing file /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="requested file permission for /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml was , defaulting to 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="reconciling file permissions for /var/lib/rancher/rke2/server/manifests/rancher/addons.yaml to 0:0 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Writing file /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="requested file permission for /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml was , defaulting to 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="reconciling file permissions for /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml to 0:0 384"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Cleaning working directory before applying /var/lib/rancher/agent/work"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=debug msg="Executing instruction 0 for plan dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Extracting image rancher/system-agent-installer-rke2:v1.21.7-rke2r1 to directory /var/lib/rancher/agent/work/20220509-101331-applied.plan/dbca27aeb930fcbe817363b947924902387587a9f40
a5387b8aa3fde60f5a4ad_0"
May 09 10:13:31 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:31Z" level=info msg="Checking local image archives in /var/lib/rancher/agent/images for index.docker.io/rancher/system-agent-installer-rke2:v1.21.7-rke2r1"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=debug msg="Found index.docker.io/rancher/system-agent-installer-rke2:v1.21.7-rke2r1 in /var/lib/rancher/agent/images/rancherd-bootstrap-images-v1.0.0.tar.zst"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="Extracting file installer.sh to /var/lib/rancher/agent/work/20220509-101331-applied.plan/dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0/installer.sh"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="Extracting file rke2.linux-amd64.tar.gz to /var/lib/rancher/agent/work/20220509-101331-applied.plan/dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0/rke2.linux-amd
64.tar.gz"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="Extracting file sha256sum-amd64.txt to /var/lib/rancher/agent/work/20220509-101331-applied.plan/dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0/sha256sum-amd64.tx
t"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="Extracting file run.sh to /var/lib/rancher/agent/work/20220509-101331-applied.plan/dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0/run.sh"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="Running command: sh [-c run.sh]"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="[dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0:stderr]: + SA_INSTALL_PREFIX=/usr/local"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="[dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0:stderr]: + mkdir -p /var/lib/rancher/rke2"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="[dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0:stderr]: + SAI_FILE_DIR=/var/lib/rancher/rke2/system-agent-installer"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="[dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0:stderr]: + RESTART_STAMP_FILE=/var/lib/rancher/rke2/system-agent-installer/rke2_restart_stamp"
May 09 10:13:32 harvester002 rancher-system-agent[14578]: time="2022-05-09T10:13:32Z" level=info msg="[dbca27aeb930fcbe817363b947924902387587a9f40a5387b8aa3fde60f5a4ad_0:stderr]: + RKE2_SA_ENV_FILE_NAME=rke2-sa.env"
...
```

**Comment by w13915984028** [comment]
The issue was solved, and the doc was also updated.

**Comment by ER-EPR** [comment]
I still experience this problem in 1.2.1，and also [BUG] Unable to join new v1.2.0 node to v1.2.0 cluster #4511 simultaneously. Is there a proper way to reconfigure the register URL for both harvester node join, and rke2 node promotion, when changing from VIP IP to FQDN and change the corresponding SSL certificate.

**Comment by starbops** [comment]
Hi @ER-EPR, for #4511, did you try the [workaround](https://docs.harvesterhci.io/v1.2/install/index#fail-to-join-nodes-using-fqdn-to-a-cluster-which-has-custom-ssl-certificate-configured) and still unable to join the node? Basically, the docs instruct you to add the CA to the node's trust list if you already have `ssl-certificate` configured before joining the node.

**Comment by ER-EPR** [comment]
> Hi @ER-EPR, for #4511, did you try the [workaround](https://docs.harvesterhci.io/v1.2/install/index#fail-to-join-nodes-using-fqdn-to-a-cluster-which-has-custom-ssl-certificate-configured) and still unable to join the node? Basically, the docs instruct you to add the CA to the node's trust list if you already have `ssl-certificate` configured before joining the node.

Thanks for the suggestion. I successfully add the nodes using work around from #4511 and #2194. But I don't know whether there will be another problem somewhere, so I want to properly change these settings. I use a let's encrypt SSL certificate and CA. Also I discover another issue #4683 while debugging this node joining problem, which didn't exhibit notable effect until I decide to upgrade from 1.2.0 to 1.2.1 and failed. Only node 2 go through phase 4 post-drain and success, which leads to deleting two other nodes, install from 1.2.1 ISO and rejoining them to recover the cluster. The nodes now are joined and promoted, but the local cluster under fleet-local stuck at configuring state from the day I create the 3 nodes cluster using v1.2.0 iso, while actually the control planes are ready. Is there a work around I can apply to force the state to become ready.
![image](https://github.com/harvester/harvester/assets/38782737/9d867a64-1123-49eb-b309-d0e9d930df20)
```
status:
  clientSecretName: local-kubeconfig
  clusterName: local
  conditions:
    - lastUpdateTime: '2023-09-12T14:35:18Z'
      message: marking control plane as initialized and ready
      reason: Waiting
      status: Unknown
      type: Ready
    - status: Unknown
      type: DefaultProjectCreated
    - status: Unknown
      type: SystemProjectCreated
    - lastUpdateTime: '2023-09-12T14:33:43Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-09-12T14:33:43Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-10-31T14:35:50Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-09-12T14:33:57Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2023-11-01T03:46:47Z'
      status: 'True'
      type: Provisioned
  observedGeneration: 8
  ready: true
```

**Comment by ER-EPR** [comment]
I don't have CA trust issue, I change IP to URL using kubectl edit setting.managenent server-url to join nodes as mentioned in #4511. But also have to change server URL to internal rancher IP in /var/lib/rancher/agent/rancher2_connection_info.json to promote node as mentioned above. I want to know whether it will affect other functions or future updates.
