### ISSUE TITLE
[BUG] vm with pci passthrough  scheduling failed after node reboot

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3126]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/200774905-44f30b04-0c4c-488f-bd96-d4b858d9fd9c.png)

**workaround**
- disable passthrough 
- enable passthrough 
- restart virt-handler by using kubectl to delete the virt-handler pod on the node
```bash
kubectl -n harvester-system delete po virt-handler-k4thg
```

**To Reproduce**
1. enable pcidevices-controller in `Addons`
2. enable a pci device passthrough by `Enable passthrough `
3. reboot node
4. create vm with the passthrough pci device

**Expected behavior**

The vm is successfully scheduled.

**Support bundle**

[supportbundle_7bdd7e0e-1aea-47af-a0cf-78b0714f663e_2022-11-09T08-19-22Z.zip](https://github.com/harvester/harvester/files/9968894/supportbundle_7bdd7e0e-1aea-47af-a0cf-78b0714f663e_2022-11-09T08-19-22Z.zip)

**Environment**
 - Harvester ISO version:  v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

After reboot, host's `status.capacity[<device name>]` was changed to `0`  
![image](https://user-images.githubusercontent.com/15064560/200775041-03a5d2fa-23a1-4837-9909-b8f028bc68aa.png)

**Comment by mircea-pavel-anton** [comment]
Is there some workaround for this? I am experiencing the same behavior on both my GPUs (GTX1050 and RTX2070S) and my SAS card

**Comment by tlehman** [comment]
@mirceanton Yes, the workaround is to disable passthrough, enable passthrough and restart virt-handle by using kubectl to delete the virt-handler pod on the node

```
kubectl -n harvester-system delete po virt-handler-k4thg
```

Where you change the k4thg to match the pod name. I am working on a fix to this but it won't be out until next release

**Comment by mircea-pavel-anton** [comment]
Oh... I just now noticed it's literally the first thing mentioned in the issue...  😅 My bad, I skimmed through it and i missed that part. Thank you

**Comment by tlehman** [comment]
No problem!

**Comment by tlehman** [comment]
https://github.com/harvester/pcidevices/pull/35 has the fix for this. I verified it for the branch in that PR

**Comment by noahgildersleeve** [comment]
I tested this in v1.1.2-rc1 and it's still not working. it's looping on trying to launch the virt-launcher pod. This was on a single node machine when trying to do passthrough on a nvidia gpu.
![Greenshot 2023-03-01 18 30 06](https://user-images.githubusercontent.com/83787952/222315742-017488c7-0e5b-4190-b5d6-72b0b816f0d5.png)
[supportbundle_cd56c5ec-2d2d-468f-9273-22ea71012cc7_2023-03-02T02-20-37Z.zip](https://github.com/harvester/harvester/files/10867022/supportbundle_cd56c5ec-2d2d-468f-9273-22ea71012cc7_2023-03-02T02-20-37Z.zip)

**Comment by guangbochen** [comment]
@tlehman can u please help to check if this is already fixed in the `master-head.iso`, and move it to `ready-for-testing` if is ready, thanks. Additionally, can u please help to update the `Pre Ready-For-Testing Checklist`.

**Comment by tlehman** [comment]
This is not fixed, I see the problem, the deviceplugins are being recreated on reboot, but the pcidevices are not being bound to vfio-pci. I can fix this but it won't be done until tomorrow around noon. What time is the go/no-go for release?

**Comment by noahgildersleeve** [comment]
I took a look at this with `v1.1.2-rc3` with @tlehman. It looks like it's still broke. However I think it's because the `vfio` driver for the GPU isn't being reloaded on reboot. You can test this by enabling pci passthrough on the gpu. Checking for vfio with `lspci -s 0000:08:00.0 -v | grep vfio` (replace the pci address with the address from the pci devices list). Reboot, then run the command again. It won't show up. This means it won't be added to a VM. This seems to be the underlying cause of the other issues.

Workaround: Disable pci passthrough, then enable it again. If there is a VM that has this assigned you can do the same thing because you can disable pci passthrough on an assigned PCI device. Then you just reboot the VM/start it if it's not running. 

I'm not sure if being able to disable passthrough on an assigned device is as working as designed CC @rebeccazzzz @guangbochen. Assigned devices are assigned based on name and PCI address. This probably isn't a big deal since you can't assign the same PCI device twice, although you can disable passthrough on one. I'm not sure if that works on running VMs. 

[supportbundle_be41fb70-8473-4d8f-b43f-78fe7573d300_2023-03-13T19-44-32Z.zip](https://github.com/harvester/harvester/files/10961308/supportbundle_be41fb70-8473-4d8f-b43f-78fe7573d300_2023-03-13T19-44-32Z.zip)

**Comment by ibrokethecloud** [comment]
the rebind on reboot issue has been addressed with this change: https://github.com/harvester/pcidevices/pull/51

**Comment by bk201** [comment]
@tlehman Could you add a test plan for QA.

**Comment by noahgildersleeve** [comment]
Retested with `v1.1-e1905897-head`. I also did cuda samples verification for the GPU both before and after the reboot to verify that it was working properly.

## Verification steps
1. Enable PCI devices addon
2. Add GPU for passthrough
3. Verify that `vfio` is enabled on device with `lspci -s 0000:08:00.0 -v | grep vfio`
4. Add GPU to VM
5. Reboot node
6. Verify that `vfio` is still enabled with `lspci -s 0000:08:00.0 -v | grep vfio`
7. Make sure that VM that has GPU assigned comes back up.
