### ISSUE TITLE
[BUG] User Data and Network Data display incorrectly when provisioning RKE2 via terraform-provider-rancher2

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3598]
### Describe the bug
When provision RKE2 via `terraform-provider-rancher2`, **UserData** and **NetworkData** become garbled.
![image](https://user-images.githubusercontent.com/5169694/222478006-47c80988-c251-45e9-92a3-1eba3c4f43ad.png)

### To Reproduce
1. Install Harvester with any nodes
2. Install Rancher
3. Login to Harvester dashboard, create an image for VM creation
4. Create a VM Network which able to access Rancher
5. Install **terraform-provider-rancher2**
    - Use https://github.com/rancher/terraform-provider-rancher2/pull/1051#issue-1520440132 or new version after this PR
6. Apply code snippet in **Additional content**
    - Update all **UPPER_CASE** info in the code snippet
7. View RKE2 cluster config after It provisioned (configuration will not able to view before RKE2 provisioned)

### Expected behavior
**UserData** and **NetworkData** should display as human readable.

## Environment:
 - Harvester ISO version: **v1.1-a002d078-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**
* Rancher Version:
    - **v2.7-c24fb8b0869a0b445f55b3307c6ed4582e147747-head (Docker Image: 216bef921570)**
    - **v2.6-a55f968896341f311fc8302b3ed6247da3c13900-head (Docker Image: 122aa2f1b66b)**

### Additional context
ref to https://github.com/rancher/terraform-provider-rancher2/pull/1051#issuecomment-1452094194

Code snippet as below:
```terraform
terraform {
  required_providers {
    rancher2 = {
      source = "rancher/rancher2"
      version = "0.0.0-master"
    }
  }
}


provider "rancher2" {
  api_url    = "RANCHER_URL"
  access_key = "RANCHER_ACCESS_TOKEN"
  secret_key = "RANCHER_SECRET_KEY_FOR_TOKEN"
  insecure = true
}


data "rancher2_cluster_v2" "foo-harvester" {
  name = "vm"
}

# Create a new Cloud Credential for an imported Harvester cluster
resource "rancher2_cloud_credential" "foo-harvester" {
  name = "foo-harvester"
  harvester_credential_config {
    cluster_id = data.rancher2_cluster_v2.foo-harvester.cluster_v1_id
    cluster_type = "imported"
    kubeconfig_content = data.rancher2_cluster_v2.foo-harvester.kube_config
  }
}

# Create a new rancher2 machine config v2 using harvester node_driver
resource "rancher2_machine_config_v2" "foo-harvester-v2" {
  generate_name = "harv"
  harvester_config {
    vm_namespace = "default"
    cpu_count = "2"
    memory_size = "4"
    disk_info = <<EOF
    {
        "disks": [{
            "imageName": "IMAGE_ID",
            "size": 40,
            "bootOrder": 1
        },{
            "storageClassName": "harvester-longhorn",
            "size": 5,
            "bootOrder": 2
        }]
    }
    EOF
    network_info = <<EOF
    {
        "interfaces": [{
            "networkName": "VM_NETWORK_ID",
            "macAddress": ""
        },{
            "networkName": "VM_NETWORK_ID",
            "macAddress": ""
        }]
    }
    EOF
    ssh_user = "ubuntu"
    user_data = <<EOF
#cloud-config
password: password
chpasswd: {expire: False}
sshpwauth: True
EOF
    network_data = <<EOF
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: dhcp
EOF
  }
}

resource "rancher2_cluster_v2" "foo-harvester-v2" {
  name = "harv2"
  kubernetes_version = "v1.24.9+rke2r2"
  rke_config {
    machine_pools {
      name = "pool1"
      cloud_credential_secret_name = rancher2_cloud_credential.foo-harvester.id
      control_plane_role = true
      etcd_role = true
      worker_role = true
      quantity = 1
      machine_config {
        kind = rancher2_machine_config_v2.foo-harvester-v2.kind
        name = rancher2_machine_config_v2.foo-harvester-v2.name
      }
    }
    machine_selector_config {
      config = {
        cloud-provider-name = ""
      }
    }
    machine_global_config = <<EOF
cni: "calico"
disable-kube-proxy: false
etcd-expose-metrics: false
EOF
    upgrade_strategy {
      control_plane_concurrency = "10%"
      worker_concurrency = "10%"
    }
    etcd {
      snapshot_schedule_cron = "0 */5 * * *"
      snapshot_retention = 5
    }
    chart_values = ""
  }
}
```

**Comment by futuretea** [comment]
This issue is not related to the multi disks and multi network issue，moved this issue to 1.2.0. cc @lanfon72

**Comment by WuJun2016** [comment]
Hi,  @lanfon72 Can you help verify this problem first ？ It has been merged into rancher 2.7.2

**Comment by lanfon72** [comment]
@WuJun2016 this also break on `v2.6-head`, are we going to fix them on `v2.6`?

**Comment by WuJun2016** [comment]
> @WuJun2016 this also break on `v2.6-head`, are we going to fix them on `v2.6`?


It won't be fixed in `2.6.11` because it's already released,  
Maybe it should be fixed in `2.6-head`,  But there is no planned version  （rancher `2.6.12`） right now

**Comment by lanfon72** [comment]
## Tested with following cases:
- UI fixed on Rancher `v2.7-211409c9a689d8ee4d801ed1bce1d887b0fb4b00-head` with Harvester `v1.1.2-rc3`, but RKE2 provision stuck.
- UI not fixed on Rancher `v2.7.2-rc5` with Harvester `v1.1.2-rc3`, but RKE2 provisioned successfully.

**Comment by lanfon72** [comment]
Verified this has been fixed.

![image](https://user-images.githubusercontent.com/5169694/225287837-e4180e3e-8983-4137-b709-e7fe901801d6.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1.2-rc3**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-cd1a71624a94de993d471ce8a643cf4d2dbb75a6-head**

### Verify Steps:
- Follow **Step to reproduce** in https://github.com/harvester/harvester/issues/3598#issue-1611539260
- Update **userData** in code snippet to include `qemu-guest-agent`[^1] as below:
```yaml
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
```

[^1]: we changed to not install `qemu-guest-agent` automatically when using terraform in https://github.com/harvester/harvester/issues/3392
