### ISSUE TITLE
[BUG] After upgrade complete, we can still see the hvst-upgrade image display on the vm and volume creation page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3604]
**Describe the bug**

After we successfully upgrade from v1.1.1 to v1.1.2-rc1, and try to create a VM and volume

We can still see the `hvst-upgrade` image display on the image list of virtual machine page 
![image](https://user-images.githubusercontent.com/29251855/223346759-bc65a324-b094-4ecc-9c40-caa232dc7936.png)

We can also see the `hvst-upgrade` image display on the image list of volume page 
![image](https://user-images.githubusercontent.com/29251855/223346874-eb1454ee-0536-41c8-a826-ab114b44b25c.png)

**To Reproduce**
1. Prepare a 2 nodes Harvester cluster of v1.1.1 release 
2. Provision a RKE2 guest cluster 
3. Upgrade to v1.1.2-rc1 
4. Wait until the upgrade complete
5. Create a virtual machine, check the images list 
6. Create a volume, check the images list

**Expected behavior**

The hvst-upgrade image should not exist on the image list of vm and volume page 

**Support bundle**

[supportbundle_2df5f22c-bf4c-41ad-a11f-e72b673a480a_2023-03-07T07-55-07Z.zip](https://github.com/harvester/harvester/files/10906855/supportbundle_2df5f22c-bf4c-41ad-a11f-e72b673a480a_2023-03-07T07-55-07Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1 to v1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 nodes bare machines
 
**Additional context**

**Comment by bk201** [comment]
@TachunLin Please help monitor if this still happens after 1.1.2-rc3.

**Comment by WuJun2016** [comment]
> @TachunLin Please help monitor if this still happens after 1.1.2-rc3.

@bk201  I think it still exists and the UI will be fixed in `v1.2.0`.   (Unless the backend deletes the updated image immediately after the successful upgrade)

**Comment by bk201** [comment]
@WuJun2016 Yes, the backend delete the image. We think it should be fixed after https://github.com/harvester/harvester/pull/3508 as well.

**Comment by lanfon72** [comment]
ref to #1855

**Comment by lanfon72** [comment]
For same version upgrade (`v1.1.2` -> `v1.1.2`), the volume for upgrade still exists, but VM and image deleted.
![image](https://user-images.githubusercontent.com/5169694/234870254-abb32f85-be7c-4be0-a0f6-865afd3bf848.png)
![image](https://user-images.githubusercontent.com/5169694/234870095-7b1b4180-e16f-4449-93b9-7395e72bc7ce.png)
![image](https://user-images.githubusercontent.com/5169694/234870855-fe74d8ef-7fd3-4707-a583-1c90b8cf471d.png)

**Comment by bk201** [comment]
@starbops Could you check Lanfon's comment, is the volume to be kept intentionally?

**Comment by starbops** [comment]
Yes, the log-archive volume and downloader pod are kept intentionally for users to download the upgradelog archive even after the upgrade ends. The volume and pod will be cleaned up after the user click the "dismiss it" button on the upgrade dialog.

@lanfon72 do you remember if you clicked the "dismiss it" button on the upgrade dialog? If you clicked it or remove the upgrade CR, and the volume was still there, there might be some problem.

**Comment by lanfon72** [comment]
I can double confirm whether it will be deleted after user **dismiss** upgrade info, but I thought UI will still need to fix the amount as user can't access the volume.

**Comment by lanfon72** [comment]
Confirmed the volume will be deleted after **dissmiss** upgrade info.

**Comment by bk201** [comment]
Feel free to open it if it happens again. The logging volume is only deleted when clicking dismiss.
