### ISSUE TITLE
[BUG]  UI does not manage many resourceQuotas correctly

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#4981]
**Describe the bug**

Jira issue SURE-5238

**To Reproduce**
1. Go to 'Projects/Namespaces' -> Resource Quotas
2. Harvester's UI only does that for the following 4 resourceQuotas:
  * CPU Limit
  * Memory Limit
  * CPU Reservation
  * Memory Reservation

Many others are missing like:
  * configMaps
  * services.LoadBalancers

**Expected behavior**

All types should be visible

**Additional context**

![image](https://github.com/harvester/harvester/assets/26394656/196fa4e7-36c6-4e97-b9ea-ca9b83a67bfd)

**Comment by lanfon72** [comment]
Verified not fixed, move back to implement.

Tested on Harvester `v1.3.0-rc1` with Rancher `v2.7.9`, `v2.8-head`[^1] and `v2.9-head`[^2]

I checked the PR merged into dashboard's **master** but not any **release-** branch, It might be the problem.
(there was a similar PR like: https://github.com/harvester/dashboard/pull/753#issuecomment-1571531737)

[^1]: Docker Image: `rancher/rancher@sha256:0352298855f0452b651614a0f0dec4ed8708da3121ea9b325a56e8ca47218be7`
[^2]: Docker Image: `rancher/rancher@sha256:22b31c9b820ab88965f547a1d4a462856e8cea03084857eebb89d18064112a70`

**Comment by torchiaf** [comment]
@lanfon72 the fix is merged into `release-harvester-v1.3.0` branch: https://github.com/harvester/dashboard/commit/7680417f5fed1f41cb756d65bbd63b77d0d8da89 . Could you double check ?
I will investigate on it and see why it's not working.

**Comment by lanfon72** [comment]
Hi @torchiaf , I tested on Harvester `v1.3-head` with Rancher `v2.9-head`, other resources still not available.
![image](https://github.com/harvester/harvester/assets/5169694/1571d6d6-4ad1-4032-b659-a1ee7b9903c2)

To notice that I modified both `ui-resource` and `ui-index` to fetch `harvester-release-v1.3` or `harvester-release-v1.3.0`, nothing changed.

And I found that the `ui-resource` and `ui-index` is not changed for `v1.3.0-rc1` like old releases, it's point to `latest` rather than `harvester-release-v1.3` or others.  IIRC, when RC released, they should point to `harvester-release-<version>`, you can check some snapshots below:

**Harvester `v1.1.3-rc1`**
![image](https://github.com/harvester/harvester/assets/5169694/83306b61-a9a3-4468-9a41-007a9af99082)

**Harvester `v1.2.1`**
![image](https://github.com/harvester/harvester/assets/5169694/af026d4a-dd29-4a9b-8b51-ec66ed0af20b)

**Harvester `v1.2-head`**
![image](https://github.com/harvester/harvester/assets/5169694/b8ebc00c-9eba-4054-8e46-d431e6a51cec)

**Comment by torchiaf** [comment]
Ok, looks like there's something wrong with the release bundle, I'll check.

**Comment by bk201** [comment]
The ui-index problem should be fixed with: https://github.com/harvester/harvester/pull/5084

**Comment by torchiaf** [comment]
We identified the root cause of the bug. It seems that Harvester UI is loading the Projects/Namespaces tab from Rancher manager UI bundle, where this bug is still present.
It will require a new fix on Harvester dashboard + a further investigation on how UI components are loaded when H. is embedded in Rancher manager.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.3.0-rc2** with Rancher `v2.7-head`, `v2.8-head`, `v2.9-head`
* **ui-source** Option: **External**
