### ISSUE TITLE
[BUG] VM created over 20 mins still shows `VirtualMachine generation is 2, but latest observed generation is 1`

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6375]
**Describe the bug**
Even VM created over 30 mins, it still shows `VirtualMachine generation is 2, but latest observed generation is 1`.
Note that we had similiar issue in `v1.3.0`, see #4909.

**To Reproduce**
1. Create a 2 nodes `harvester-v1.3.2-rc1`
2. Create VM image `ubuntu-24.04-noble-server-cloudimg-amd64.img`
3. Create VM network `mgmt-vlan1`
4. Create VM `noble`

**Expected behavior**
According to previous behavior, `VirtualMachine generation...` message will gone in few minutes.

**Support bundle**
[supportbundle_generation_msg_2024-08-19T08-20-04Z.zip](https://github.com/user-attachments/files/16657712/supportbundle_generation_msg_2024-08-19T08-20-04Z.zip)

**Environment**
* `harvester-v1.3.2-rc1`
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: `Auto`

**Additional context**
1. Found during verifying #6321 
1. Seems not related to OS version cuz not only hit in ubuntu **noble** but also **jammy**.
   ![image](https://github.com/user-attachments/assets/b074a348-9ab6-4ce1-b9ff-ec9343a5fab2)

**Comment by w13915984028** [comment]
@albinsun Did you see such on Harvester v1.4.0 / master-head cluster? thanks.

**Comment by w13915984028** [comment]
I did not notice it on master-head; let me double check on v1.3.2.

**Comment by w13915984028** [comment]
Easy to produce on v1.3.2.
![image](https://github.com/user-attachments/assets/57bafb3e-e8e5-4570-abe0-1339c0d16253)

vm
```

apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      harvesterhci.io/vmRunStrategy: RerunOnFailure
      harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"vm1-disk-0-fzg2n","annotations":{"harvesterhci.io/imageId":"default/image-mbhxj"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"4Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-mbhxj"}}]'
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      network.harvesterhci.io/ips: '[]'
    creationTimestamp: "2024-08-19T10:18:53Z"
    finalizers:
    - harvesterhci.io/VMController.UnsetOwnerOfPVCs
    - kubevirt.io/virtualMachineControllerFinalize
    generation: 2
    labels:
      harvesterhci.io/creator: harvester
...    created: true
    desiredGeneration: 2
    observedGeneration: 1
    printableStatus: Running
    ready: true
    volumeSnapshotStatuses:
    - enabled: false
      name: disk-0
      reason: 2 matching VolumeSnapshotClasses for longhorn-image-mbhxj
    - enabled: false
      name: cloudinitdisk
      reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
kind: List
metadata:
  resourceVersion: ""
```
vmi
```
apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  metadata:
    annotations:
      harvesterhci.io/sshNames: '[]'
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      kubevirt.io/vm-generation: "1"
    creationTimestamp: "2024-08-19T10:18:53Z"
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    - foregroundDeleteVirtualMachine
    - wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs
    - wrangler.cattle.io/harvester-lb-vmi-controller
    generation: 9
    labels:
      harvesterhci.io/vmName: vm1
      kubevirt.io/nodeName: harv21
    name: vm1
```

**Comment by w13915984028** [comment]
This issue is my fault in privious PR https://github.com/harvester/harvester/pull/6225/files#diff-0cb3042c9e2b11288fdf37ca3c83913c56107834daf023691f52e35dc306c0ddR74; it affect v1.4, v1.3 and master-head.

A new PR https://github.com/harvester/harvester/pull/6379 is added to master-head to solve, and will backport to v1.4, v1.3.

cc @bk201 @FrankYang0529 , thanks.

**Comment by albinsun** [comment]
> @albinsun Did you see such on Harvester v1.4.0 / master-head cluster? thanks.

Hi @w13915984028 ,
I also hit in _v1.4.0-dev-20240819_
SB: [supportbundle_VMGeneration140dev20240819.zip](https://github.com/user-attachments/files/16661686/supportbundle_VMGeneration140dev20240819.zip)

![image](https://github.com/user-attachments/assets/7f698ca5-56aa-424a-95ab-cc35db8e6e8c)

* VM
   ```
  apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      harvesterhci.io/vmRunStrategy: RerunOnFailure
      harvesterhci.io/volumeClaimTemplates: >-
        [{"metadata":{"name":"local-jammy-disk-0-c3vz2","annotations":{"harvesterhci.io/imageId":"default/image-hjdmz"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-hjdmz"}}]
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      network.harvesterhci.io/ips: '[]'
    creationTimestamp: '2024-08-19T14:15:44Z'
    finalizers:
      - kubevirt.io/virtualMachineControllerFinalize
      - wrangler.cattle.io/VMController.CleanupPVCAndSnapshot
    generation: 2
    ...
    created: true
    desiredGeneration: 2
    observedGeneration: 1
    printableStatus: Running
    ready: true
    runStrategy: RerunOnFailure
    volumeSnapshotStatuses:
      - enabled: false
        name: disk-0
        reason: 2 matching VolumeSnapshotClasses for longhorn-image-hjdmz
      - enabled: false
        name: cloudinitdisk
        reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
   ```
* VMI
   ```
  {
  "apiVersion": "kubevirt.io/v1",
  "kind": "VirtualMachineInstance",
  "metadata": {
  "annotations": {
  "harvesterhci.io/sshNames": "[]",
  "kubevirt.io/latest-observed-api-version": "v1",
  "kubevirt.io/storage-observed-api-version": "v1",
  "kubevirt.io/vm-generation": "1"
  },
  "creationTimestamp": "2024-08-19T14:15:44Z",
  "fields": [ 8 items
  "local-jammy",
  "33m",
  "Running",
  "192.168.0.51",
  "harvester-node-1",
  "True",
  "True",
  null
  ],
  "finalizers": [ 3 items
  "kubevirt.io/virtualMachineControllerFinalize",
  "foregroundDeleteVirtualMachine",
  "wrangler.cattle.io/harvester-lb-vmi-controller"
  ],
  "generation": 13,
  "labels": {
  "harvesterhci.io/vmName": "local-jammy",
  ...
   ```

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/c770824f-7436-4354-bb11-5bf6721ce7aa)

Test Information
----
* Environment: **qemu/KVM 2 nodes + 1 witness**
* Harvester Version: **v1.4.0-dev-20240918**
* **ui-source** Option: **Auto**

### Verify Steps
- Follow steps to reproduce in https://github.com/harvester/harvester/issues/6375#issue-2472770993

**Comment by AdamJSoftware** [comment]
I am still experiencing this issue running on Harvester 1.4.0
<img width="1226" alt="Screenshot 2024-12-29 at 11 21 26 AM" src="https://github.com/user-attachments/assets/93055a7c-9f78-4c74-9f07-2be98f56e747" />

**Comment by bk201** [comment]
@AdamJSoftware Thanks, please refer to https://github.com/harvester/harvester/issues/6844

**Comment by angelosnm** [comment]
Experiencing same issue here with 1.4.1
