### ISSUE TITLE
[BUG] API extension group needs upgrade

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#648]
Warning in the Harvester log
```
apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by guangbochen** [comment]
will need to bump the API extension version of the upstream dependency framework of the wrangler.

**Comment by guangbochen** [comment]
https://github.com/rancher/wrangler/pull/154/files

**Comment by guangbochen** [comment]
- [x] https://github.com/rancher/wrangler/pull/154
- [x] https://github.com/rancher/steve/pull/16

**Comment by guangbochen** [comment]
CRDs(v1) created by Harvester are not compatible with CRDs(v1beta1) used in rancher v2.5.7 https://github.com/harvester/harvester/issues/749,
need to bump after the Rancher updates its CRD API version.

**Comment by guangbochen** [comment]
this should be addressed with https://github.com/harvester/harvester/pull/998, the `CustomResourceDefinition is deprecated` error is expected to be gone in the harvester logs.

**Comment by juadk** [comment]
I've installed the latest harvester master-head branch (`master-ada6b573-head`) and I still see some warnings about the API version for CRDs but not in the harvester logs directly, so I tend to say ok.

`cert-manager-cainjector-74459fcc56-ql6st_cert-manager_cert-manager-5c454923457a864d4724b8250c81ee3e0181484e8c5e27454d7e3963bce70bce.log:2021-08-04T10:20:17.076558032Z stderr F W0804 10:20:17.076341       1 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

`harvester-webhook-6d94fd86cb-fvs2m_harvester-system_harvester-webhook-774ef67c2719e93a3853cf89c174658dbdcb61246c7a78ce4d26047308192f87.log:2021-08-04T10:20:26.908500481Z stderr F W0804 10:20:26.908309       7 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

`rancher-76c6f7cf65-bftds_cattle-system_rancher-ec085f7f0147310fe6b4f078d8250402e0ac6db41b035cbf8c84429bb325b2f3.log:2021-08-04T10:23:43.999486964Z stderr F W0804 10:23:43.999192      31 warnings.go:80] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

@gitlawr @guangbochen WDYT?

**Comment by guangbochen** [comment]
I think it's better for us to fix those related CRD as well, thanks

**Comment by FrankYang0529** [comment]
* [ ] https://github.com/rancher/wrangler/pull/180

**Comment by yasker** [comment]
The majority of the CRD update has been done. Since Harvester has pinned down an underlying Kubernetes version, this is not a release blocker for v0.3.0. Move to v1.0.0.

**Comment by yasker** [comment]
We cannot fix the issues in the controllers at this moment due to https://github.com/rancher/wrangler/pull/180#issuecomment-933787561 . Move the issue to beyond `future`, waiting for Rancher team to figure out a solution.
