### ISSUE TITLE
[BUG] vGPU SR-IOV not getting visible on nvidea l40S

### ISSUE THREAD

**Issue by samueldewever** [harvester/harvester#6487]
**Describe the bug**
We are trying to test vGPU on our Nvidia L40S GPU 
SR-IOV is enabled
Card is detected
nvidia vGPU manager is installed (535.04 driver , supporting the card)
SR-IOV GPU device is enabled
![image](https://github.com/user-attachments/assets/3873e9fc-2a75-41a1-a13d-4efbf2657b02)

PCI devices list shows the device and the 32VFs however the vGPU devices view doesn't show any devices. 
![image](https://github.com/user-attachments/assets/218bf77d-2857-4546-8a38-65198bbb861f)

No vgpudevices.devices.harvesterhci.io objects are found. 
https://github.com/user-attachments/assets/13fbd2c7-b3fe-4a72-bd27-d4242de4b102

**To Reproduce**
1. Install card - install drivers via nvidia-toolkit - enable card  - no vgpudevices detected afterwards

**Expected behavior**
We expect to see a list of vGPU devices under the vGPU devices menu

**Support bundle**

**Environment**
 - Harvester ISO version: 1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell Poweredge R650 with nvidia L40S GPU 

**Additional context**

**Comment by samueldewever** [comment]
Support bundle send via mail (wetransfer)

**Comment by bk201** [comment]
We received the SB, @ibrokethecloud can you help check if possible? Thanks

**Comment by noahgildersleeve** [comment]
@samueldewever what version of the KVM driver are you using in your HTTP endpoint for the nvidia-driver-toolkit? For instance I have been using `NVIDIA-Linux-x86_64-550.90.05-vgpu-kvm.run`.

Also I can't see the second image in your bug report. The one under this line
`PCI devices list shows the device and the 32VFs however the vGPU devices view doesn't show any devices.`

Could you add that again? The first image shows up fine.

**Comment by ibrokethecloud** [comment]
a support bundle would be appreciated

**Comment by samueldewever** [comment]
> a support bundle would be appreciated

@ibrokethecloud  this has been send before via mail and confirmed by @bk201 that its well received.

**Comment by samueldewever** [comment]
> @samueldewever what version of the KVM driver are you using in your HTTP endpoint for the nvidia-driver-toolkit? For instance I have been using `NVIDIA-Linux-x86_64-550.90.05-vgpu-kvm.run`.
> 
> Also I can't see the second image in your bug report. The one under this line `PCI devices list shows the device and the 32VFs however the vGPU devices view doesn't show any devices.`
> 
> Could you add that again? The first image shows up fine.

Hi @noahgildersleeve : we have tried both NVIDIA-Linux-x86_64-535.183.04-vgpu-kvm.run and 550.90.05-vgpu-kvm.run. Both gave the same result and should both support the L40s cards.

I will reupload the images this afternoon.

**Comment by samueldewever** [comment]
@noahgildersleeve I have reuploaded the screenshot of the PCI devices. You can see it find 33 devices for hte L40s card. My feeling is that actually this devices should not show up under the PCI devices but under the vGPU devices ...

**Comment by ibrokethecloud** [comment]
are you able to please resend the support bundle?

**Comment by samueldewever** [comment]
> are you able to please resend the support bundle?

@ibrokethecloud just sent via mail.

**Comment by ibrokethecloud** [comment]
the devices are not visible because the controller cannot reconcile the info from /sys fs

```
time="2024-09-03T07:36:50Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T07:41:19Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T07:45:49Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T07:50:17Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T07:54:52Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T07:59:24Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T08:03:56Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T08:08:27Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T08:12:59Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T08:17:39Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"                                                                                                                                                                         
time="2024-09-03T08:22:05Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"  
```

are you able to please provide us the result of `ls -l /sys/class/mdev_bus/0000:ae:00.4/` on the gpu node?

**Comment by samueldewever** [comment]
> ```
> time="2024-09-03T08:22:05Z" level=error msg="error syncing 'harvester04': handler reconcile-pcidevices: error setting VGPU devices for node harvester04: error identifying vgpu devices: could not get mdev_supported_types directory information for device: 0000:ae:00.4, er
> r: lstat /sys/class/mdev_bus/0000:ae:00.4/mdev_supported_types: no such file or directory, requeuing"  
> ```

@ibrokethecloud 
The directory mentioned doesn't exist. 
If we search for 0000:ae:00.4 we find them back here:

 rancher@harvester04:~> ls /sys/bus/pci/devices | grep 0000:ae
0000:ae:00.0
0000:ae:00.4
0000:ae:00.5
0000:ae:00.6
0000:ae:00.7
0000:ae:01.0
0000:ae:01.1
0000:ae:01.2
0000:ae:01.3
0000:ae:01.4
0000:ae:01.5
0000:ae:01.6
0000:ae:01.7
0000:ae:02.0
0000:ae:02.1
0000:ae:02.2
0000:ae:02.3
0000:ae:02.4
0000:ae:02.5
0000:ae:02.6
0000:ae:02.7
0000:ae:03.0
0000:ae:03.1
0000:ae:03.2
0000:ae:03.3
0000:ae:03.4
0000:ae:03.5
0000:ae:03.6
0000:ae:03.7
0000:ae:04.0
0000:ae:04.1
0000:ae:04.2
0000:ae:04.3

and a reference in this directory:
rancher@harvester04:~> ls /sys/bus/pci/drivers/vfio-pci/
0000:8a:01.0  0000:8a:01.4  0000:8a:11.0  0000:8a:11.4  0000:ae:00.4  0000:ae:01.0  0000:ae:01.4  0000:ae:02.0  0000:ae:02.4  0000:ae:03.0  0000:ae:03.4  0000:ae:04.0  bind       uevent
0000:8a:01.1  0000:8a:01.5  0000:8a:11.1  0000:8a:11.5  0000:ae:00.5  0000:ae:01.1  0000:ae:01.5  0000:ae:02.1  0000:ae:02.5  0000:ae:03.1  0000:ae:03.5  0000:ae:04.1  module     unbind
0000:8a:01.2  0000:8a:01.6  0000:8a:11.2  0000:8a:11.6  0000:ae:00.6  0000:ae:01.2  0000:ae:01.6  0000:ae:02.2  0000:ae:02.6  0000:ae:03.2  0000:ae:03.6  0000:ae:04.2  new_id
0000:8a:01.3  0000:8a:01.7  0000:8a:11.3  0000:8a:11.7  0000:ae:00.7  0000:ae:01.3  0000:ae:01.7  0000:ae:02.3  0000:ae:02.7  0000:ae:03.3  0000:ae:03.7  0000:ae:04.3  remove_id

**Comment by ibrokethecloud** [comment]
are you please able to check gpu mode is enabled https://developer.nvidia.com/displaymodeselector

**Comment by samueldewever** [comment]
> are you please able to check gpu mode is enabled https://developer.nvidia.com/displaymodeselector

Checked and yes its enavbled in compute mode.

**Comment by samueldewever** [comment]
> > are you please able to check gpu mode is enabled https://developer.nvidia.com/displaymodeselector
> 
> Checked and yes its enavbled in compute mode.

ALso tried once to change it to graphics mode. In that case I cannot enable the SR-IOV GPU adaapter.
Changed it back to compute now. 

Problem remains the same. vGPU Devices not becoming available.

**Comment by samueldewever** [comment]
@ibrokethecloud I was still doing some troubleshooting and find the following in dmesg after the nvidia kvm comletes:
Sep 16 15:47:42 harvester04 kernel: nvidia 0000:ae:00.0: Direct firmware load for nvidia/550.90.05/gsp_ga10x.bin failed with error -2
Sep 16 15:47:42 harvester04 kernel: NVRM: RmFetchGspRmImages: No firmware image found
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: RmInitAdapter failed! (0x61:0x56:1697)
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: rm_init_adapter failed, device minor number 0
Sep 16 15:47:42 harvester04 kernel: nvidia 0000:ae:00.0: Direct firmware load for nvidia/550.90.05/gsp_ga10x.bin failed with error -2
Sep 16 15:47:42 harvester04 kernel: NVRM: RmFetchGspRmImages: No firmware image found
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: RmInitAdapter failed! (0x61:0x56:1697)
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: rm_init_adapter failed, device minor number 0
Sep 16 15:47:42 harvester04 nvidia-vgpud[76102]: error: failed to attach device: 59
Sep 16 15:47:42 harvester04 nvidia-vgpud[76102]: error: failed to read pGPU information: 9
Sep 16 15:47:42 harvester04 nvidia-vgpud[76102]: error: failed to send vGPU configuration info to RM: 9
Sep 16 15:47:42 harvester04 nvidia-vgpu-mgr[76120]: error: vmiop_env_log: Failed to attach device: 0x59 (gpuId 0xae00)
Sep 16 15:47:42 harvester04 kernel: nvidia 0000:ae:00.0: Direct firmware load for nvidia/550.90.05/gsp_ga10x.bin failed with error -2
Sep 16 15:47:42 harvester04 kernel: NVRM: RmFetchGspRmImages: No firmware image found
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: RmInitAdapter failed! (0x61:0x56:1697)
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: rm_init_adapter failed, device minor number 0
Sep 16 15:47:42 harvester04 kernel: nvidia 0000:ae:00.0: Direct firmware load for nvidia/550.90.05/gsp_ga10x.bin failed with error -2
Sep 16 15:47:42 harvester04 kernel: NVRM: RmFetchGspRmImages: No firmware image found
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: RmInitAdapter failed! (0x61:0x56:1697)
Sep 16 15:47:42 harvester04 kernel: NVRM: GPU 0000:ae:00.0: rm_init_adapter failed, device minor number 0

**Comment by samueldewever** [comment]
@ibrokethecloud 
I did more research today and came across this article:
https://forums.developer.nvidia.com/t/kernel-direct-firmware-load-for-nvidia-550-90-05-gsp-ga10x-bin-failed-with-error-2/301117/3

What I did:
- I went to the harvester-nvidia-driver-toolkit pod shell 
- Indeed could see that nvidia-smi was not detecting the card because of the error in firmware load
- i disabled in the pod the NVreg_EnableGpuFirmware=0 and installed version 535.183.04 afterwards
- afterwards I didn't saw the error of gsp_ga10x not being able to nvidia-smi detected the device
- I runned sriov-manage -e ALL to enable the VF
- I runned nvidia_vgpu_mgr afterwards

Immediatly afterwards the mdev interfaces got created and I can now see the vgpu devices. 

tested the same with nvidia version 550, here the workaround is not working. Even with GPUFirmware=0 it still tries to load the firmware and fails. 

On short term, a workaround could be that the nvidia_driver_toolkit disable GPUFirmware by default so we could run with 535 version.

However we still needs to understand why loading the firmware fails. Error -2 points me to 'file not exist', however I checked and the files are available in the right place.

**Comment by samueldewever** [comment]
@ibrokethecloud

I did additional troubleshooting. 
When going into the pod of the nvidia-driver-toolkit I could see that the nvidia-smi was not detecting the card because of the driver load failure. Because of that , nvidia-vgpu-mgr couldn't start as well.

As ther error was 'failed with error -2', it pointed me to the file not found. I realized that, as this firmware get loaded via nvidia (kernel module), it is probably going to look for the driver on the underlying OS, while the files are in the pod. 

So, what I have just done:
As it runs SLE Micro , an its immutable, I couldn't just add the files in /lib/firmware/nvidia. 
I created a temp folder and created an overlay mount

mkdir -p /tmp/firmware /tmp/workdir
mount -t overlay overlay -o lowerdir=/lib/firmware/nvidia,upperdir=/tmp/firmware,workdir=/tmp/workdir /lib/firmware/nvidia

Than copied the file from the container into /tmp/firmware:
cp ./run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/59cdd4ab54bd7d4c4142efbd58a5c1a6d283e836caf8199cd056ebb14ded4769/rootfs/lib/firmware/nvidia/550.90.05/gsp_ga10x.bin /tmp/firmware/550.90.05/

Now I reloaded the nvidia module again from the pod:
nvidia-driver-runtime-fdvg6:/ # rmmod nvidia
nvidia-driver-runtime-fdvg6:/ # modprobe nvidia

the driver now loads perfectly, processes starts and mdev are now getting created. I can now see the vGPU devices.

For now I have created an systemd-service to make sure the mount is created automatically at boot of the host and moved the files from /tmp to /root to overcome that they get erased at reload. This gives a temporary solution , but ofcourse is temporary as it need manual work each time a new host or vgpu version becomes available. 

This is clearly a bug. As more GPU will have the GPUFirmware support, the impact will only increase.  In version 535 you could still disable GPUFirmware, but as from 550 that doesn't seems to work anymore (see https://forums.developer.nvidia.com/t/kernel-direct-firmware-load-for-nvidia-550-90-05-gsp-ga10x-bin-failed-with-error-2/301117).

**Comment by Shifter2600** [comment]
@samueldewever 
Now that you have the vGPU profile capabilities I would be interested to know if you have any issues with passing them into a VM which is what I am up against right now.

Also I would be interested if you think we could put your fix directly into my custom nvidia-driver-toolkit to get 550 driver working
https://gitlab.com/koat-public/koat-nvidia-driver-toolkit

1st you may have an issue with the Profile if it is using lowercase in the profile names. If that is the case you need to use this fix that @ibrokethecloud gave me. 
 DaemonSet: harvester-pcidevices-controller
 Edit the config and replace the container image with
 gmehta3/pcidevices:vgpu-type-fix
 
 Next if you have issues with the VM after adding a vGPU you may need to add "model: host-passthrough"
```
 domain:
        cpu:
          cores: 12
          model: host-passthrough 
          sockets: 1
          threads: 1
```
 
Next if you have issues with the VM booting take a look at the log (here is what mine is doing https://pastebin.com/raw/RVCRyXYs ) Timed out waiting for final delete notification after calling kill.

**Comment by Shifter2600** [comment]
@samueldewever just confirmed you do not need model: host-passthrough in the VM yaml. @ibrokethecloud 

With your instruction I was able to successfully get 550 installed and the vGPU passed into the VM and nvidia-smi working in the vm using the grid driver install.  

Now the next test I am doing is does the vGPU pass in from rancher cluster manager?

**Comment by Shifter2600** [comment]
@ibrokethecloud that inclusion of the local /lib/firmware/nvidia/550.90.05/gsp_ga10x.bin works.

That was the whole problem all along as well as the case issue with the profile as well. 
@samueldewever 
I managed to get vGPU deployed node pools via Rancher Cluster Manager as well. So another big win there.

Now I just need to figure out how to deploy the proper DaemonSet to enable the nodes that have vGPU resources. I don't see any documentation on the next steps there.... How do we get the grid drivers on to the VM's that spin up with the vGPU resources? Then how do we extend that into the deployed pods?

**Comment by ibrokethecloud** [comment]
@samueldewever i will make the changes to allow loading of firmware from container into the underlying host to simplify this. This must be a recent change in the driver or specific to gpu model. I only have A30/A2 and A100s with me and I have not had to make any changes to this

**Comment by ibrokethecloud** [comment]
@samueldewever would it be possible for you amend the nvidia-driver-runtime and perform the following change

add the following volumes

```
        - name: firmware-search-path
          hostPath:
            path: /sys/module/firmware_class/parameters/path
        - name: nv-firmware
          hostPath:
            path: /run/nvidia/driver/lib/firmware
            type: DirectoryOrCreate
```

add the following volume mounts to the container 
```
            - name: firmware-search-path
              mountPath: /sys/module/firmware_class/parameters/path
            - name: nv-firmware
              mountPath: /lib/firmware
```

This should avoid the need to manually copy the files and will also ensure files are always written across post reboots

**Comment by ibrokethecloud** [comment]
just confirmed on @Shifter2600 environment and with this change to the daemonset, the GPU works fine and no firmware errors are reported

**Comment by samueldewever** [comment]
> just confirmed on @Shifter2600 environment and with this change to the daemonset, the GPU works fine and no firmware errors are reported

@ibrokethecloud :  I upgraded helm to 0.4.0 and I still face the same issue. 
I can now find back the driver files on the OS in harvester04://run/nvidia/driver/lib/firmware/nvidia/550.90.05, however during the install he looks for the driver in /lib/firmware ...

The file /sys/module/firmware_class/parameters/path was empty. I tried to echo "/run/nvidia/driver/lib/firmware/" in it , but the problems remain.

**Comment by Shifter2600** [comment]
@ibrokethecloud I got to my computer this morning and I can also confirm that the solution no longer works after a reboot of the nodes. I needed to put that fix in that @samueldewever described above.
I confirmed that the DaemondSet Yaml still has your changes with in it.

**Comment by ibrokethecloud** [comment]
thanks for the feedback.

**Comment by ibrokethecloud** [comment]
so the issue is we need to define the additional firmware search path.

This has been fixed and I have built a custom image `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240613` which includes the extra directive. 

If you could update the addon to use this image and provide feedback that would be really appreciated.

I can then figure out how to make an out of band release available for Harvester v1.3.1 and v1.3.2

**Comment by samueldewever** [comment]
> so the issue is we need to define the additional firmware search path.
> 
> This has been fixed and I have built a custom image `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240613` which includes the extra directive.
> 
> If you could update the addon to use this image and provide feedback that would be really appreciated.
> 
> I can then figure out how to make an out of band release available for Harvester v1.3.1 and v1.3.2

@ibrokethecloud 
As I said in my previous message, even after I echo the correct directory into the  /sys/module/firmware_class/parameters/path, the problem remains. 

I have done a lot of testing, but cant get it working. My feeling is that nvidia has the path somewhere hard coded. This somehow corresponds with the minimal documentation I find here: https://download.nvidia.com/XFree86/Linux-x86_64/555.58.02/README/gsp.html. 

Quote:
This processor is driven by the gsp_*.bin firmware files under **/lib/firmware/nvidia/**555.58.02/. 

If thats the case, I am afraid a overlay on the OS is the only option, unless you see another option?

**Comment by samueldewever** [comment]
@ibrokethecloud  @Shifter2600 
I have been researching more, and it really feels that nvidia vgpu kvm software has /lib/firmware hard coded somewhere. 

This is what I have done to have solution which works in a 'dynamic' way 

On the underlying OS I have created a new systemd-service
cat /etc/systemd/system/nvidia-firmware.service
[Unit]
Description=Mount overlay for NVIDIA firmware
After=network.target

[Service]
Type=oneshot
ExecStart=mkdir -p /tmp/nvidia-firmware /tmp/nvidia-workdir
ExecStart=/bin/mount -t overlay overlay -o lowerdir=/lib/firmware/,upperdir=/tmp/nvidia-firmware,workdir=/tmp/nvidia-workdir /lib/firmware/
RemainAfterExit=true

[Install]
WantedBy=multi-user.target

Created an symbolic link to make sure it auto boot at startup
ln -s /etc/systemd/system/nvidia-service.service /etc/systemd/system/multi-user.target.wants/nvidia-service.service

I am using /tmp folders for the upperdir & workdir, as you cannot use /run for an overlay (tmpfs cannot be used as upperdir) and the nvidia container will anyhow install the drivers each time after reboot, so no issue to use /tmp

There is no problem to install this service on all nodes, even if they don't have a GPU. It will in this case just create empty directories and and overlay, but shouldn't give any issue as I keep /lib/firmware as the merged folder.

Than I have changed the daemonset for the container to load the map the /tmp/nvidia-firmware towards /lib/firmware on the container. I also removed the mapping towards the firmware-search-path as its not working: 

http://sdewever.benesol.be/nvidia-driver-runtime.yaml

Now it works without manual actions. When host boots the /tmp directories and the overlay mappings is created. When the pod is started it maps the driver maps and install the drivers. 

This is best I can come-up with for now. If you have a better idea, happy to test it out. 
Might be worth opening a ticket at nvidia why they are not using/supporting the customer search path for drivers.

**Comment by ibrokethecloud** [comment]
i pushed another change to the image `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240613` and fixed the entrypoint issue i introdueced in the last change.

based on the kernel docs, the search path should be used: https://www.kernel.org/doc/html/v4.18/driver-api/firmware/fw_search_path.html

none of my GPU's seem to need the firmware.. or they are already finding the one available in /lib/firmware

any feedback on using this image would be appreciated.

**Comment by samueldewever** [comment]
> i pushed another change to the image `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240613` and fixed the entrypoint issue i introdueced in the last change.
> 
> based on the kernel docs, the search path should be used: https://www.kernel.org/doc/html/v4.18/driver-api/firmware/fw_search_path.html
> 
> none of my GPU's seem to need the firmware.. or they are already finding the one available in /lib/firmware
> 
> any feedback on using this image would be appreciated.

+ '[' -f /tmp/ready ']'
2024-09-23T11:36:07.966743302Z ++ grep '[^[:space:]]' /sys/module/firmware_class/parameters/path
+ [[ ! -z /run/nvidia/driver/lib/firmware ]]
+ echo 'WARNING: A search path is already configured in /sys/module/firmware_class/parameters/path'
2024-09-23T11:36:07.968968925Z + echo '         Retaining the current configuration'
+ modprobe firmware_class firmware_class.path=/run/nvidia/driver/lib/firmware
2024-09-23T11:36:07.969030273Z WARNING: A search path is already configured in /sys/module/firmware_class/parameters/path
         Retaining the current configuration
modprobe: FATAL: Module firmware_class not found in directory /lib/modules/5.14.21-150400.24.128-default

Is it possible that firmware_class module is not in the kernel of the image?

**Comment by samueldewever** [comment]
> > i pushed another change to the image `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240613` and fixed the entrypoint issue i introdueced in the last change.
> > based on the kernel docs, the search path should be used: https://www.kernel.org/doc/html/v4.18/driver-api/firmware/fw_search_path.html
> > none of my GPU's seem to need the firmware.. or they are already finding the one available in /lib/firmware
> > any feedback on using this image would be appreciated.
> 
> * '[' -f /tmp/ready ']'
>   2024-09-23T11:36:07.966743302Z ++ grep '[^[:space:]]' /sys/module/firmware_class/parameters/path
> * [[ ! -z /run/nvidia/driver/lib/firmware ]]
> * echo 'WARNING: A search path is already configured in /sys/module/firmware_class/parameters/path'
>   2024-09-23T11:36:07.968968925Z + echo '         Retaining the current configuration'
> * modprobe firmware_class firmware_class.path=/run/nvidia/driver/lib/firmware
>   2024-09-23T11:36:07.969030273Z WARNING: A search path is already configured in /sys/module/firmware_class/parameters/path
>   Retaining the current configuration
>   modprobe: FATAL: Module firmware_class not found in directory /lib/modules/5.14.21-150400.24.128-default
> 
> Is it possible that firmware_class module is not in the kernel of the image?

@ibrokethecloud : where you already able to check this? 
As said, the newest image is not loading (pod not starting because it cant find the firmware_class module in kernel)

**Comment by Shifter2600** [comment]
@samueldewever I was not able to get your above solution service to work. 
It was able to get the files accessible with in /tmp/nvidia-firmware but it was not able to pass that into /lib/firmware/ I believe because it is 2 levels deep. 

So what I did for now just so I can start building while this gets worked out is I just added the below to my Harvester Config and put the files in there which doesn't get removed after a reboot.
I hope a more dynamic solution will come about that would allow for new driver releases but for now I just need to start building on top of it.
```
after_install_chroot_commands:
    - "mkdir -p /lib/firmware/nvidia/550.90.05"
    - "curl -fsSL http://192.168.210.5:8080/vgpu/550.90.05/gsp_ga10x.bin -o /lib/firmware/nvidia/550.90.05/gsp_ga10x.bin"
    - "curl -fsSL http://192.168.210.5:8080/vgpu/550.90.05/gsp_tu10x.bin -o /lib/firmware/nvidia/550.90.05/gsp_tu10x.bin"
    - "chmod 644 /lib/firmware/nvidia/550.90.05/gsp_ga10x.bin /lib/firmware/nvidia/550.90.05/gsp_tu10x.bin"
    - "systemctl daemon-reload"
```

**Comment by samueldewever** [comment]
> @samueldewever I was not able to get your above solution service to work. It was able to get the files accessible with in /tmp/nvidia-firmware but it was not able to pass that into /lib/firmware/ I believe because it is 2 levels deep.
> 
> So what I did for now just so I can start building while this gets worked out is I just added the below to my Harvester Config and put the files in there which doesn't get removed after a reboot. I hope a more dynamic solution will come about that would allow for new driver releases but for now I just need to start building on top of it.
> 
> ```
> after_install_chroot_commands:
>     - "mkdir -p /lib/firmware/nvidia/550.90.05"
>     - "curl -fsSL http://192.168.210.5:8080/vgpu/550.90.05/gsp_ga10x.bin -o /lib/firmware/nvidia/550.90.05/gsp_ga10x.bin"
>     - "curl -fsSL http://192.168.210.5:8080/vgpu/550.90.05/gsp_tu10x.bin -o /lib/firmware/nvidia/550.90.05/gsp_tu10x.bin"
>     - "chmod 644 /lib/firmware/nvidia/550.90.05/gsp_ga10x.bin /lib/firmware/nvidia/550.90.05/gsp_tu10x.bin"
>     - "systemctl daemon-reload"
> ```
@ibrokethecloud 
Strange. Workaround works fine for me. What error do you than get when you run the following command on the host:

/bin/mount -t overlay overlay -o lowerdir=/lib/firmware/,upperdir=/tmp/nvidia-firmware,workdir=/tmp/nvidia-workdir /lib/firmware/

Are you sure that your workaround is going to work as everything in /lib/firmware is read only file system at host so i think the mkdir is going to fail. That's why i had to do the overlay. 

Test from a node without overlay mount active:
harvester01:~ # mkdir -p /lib/firmware/nvidia/550.90.05
**mkdir: cannot create directory ‘/lib/firmware/nvidia/550.90.05’: Read-only file system**
harvester01:~ #

**Comment by Shifter2600** [comment]
@samueldewever 
Figured it out.
The service enable and start was incorrect from your writeup.
```
ln -s /etc/systemd/system/nvidia-service.service /etc/systemd/system/multi-user.target.wants/nvidia-service.service
<>
ln -s /etc/systemd/system/nvidia-firmware.service /etc/systemd/system/multi-user.target.wants/nvidia-firmware.service
```
So i got this into a deploy as code state. @ibrokethecloud 
I added this to my config. The service gets added and starts.
```
  write_files:
    # Write the systemd service for NVIDIA firmware overlay with cleanup
    - content: |
        [Unit]
        Description=Mount overlay for NVIDIA firmware
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=mkdir -p /tmp/nvidia-firmware /tmp/nvidia-workdir
        ExecStart=/bin/mount -t overlay overlay -o lowerdir=/lib/firmware/,upperdir=/tmp/nvidia-firmware,workdir=/tmp/nvidia-workdir /lib/firmware/
        RemainAfterExit=true

        [Install]
        WantedBy=multi-user.target
      path: /etc/systemd/system/nvidia-firmware.service
      permissions: '0644'

  after_install_chroot_commands:
    - "ln -s /etc/systemd/system/nvidia-firmware.service /etc/systemd/system/multi-user.target.wants/nvidia-firmware.service"
```

**Comment by ibrokethecloud** [comment]
the firmware loader is enabled in the kernel 
```
vgpu-01:~ # more /boot/config-5.14.21-150400.24.128-default  |grep FW_LOADER
CONFIG_FW_LOADER=y
CONFIG_FW_LOADER_PAGED_BUF=y
CONFIG_FW_LOADER_USER_HELPER=y
# CONFIG_FW_LOADER_USER_HELPER_FALLBACK is not set
CONFIG_FW_LOADER_COMPRESS=y
```

**Comment by samueldewever** [comment]
@ibrokethecloud : Once the change you have done to make /lib/firmware RW on the installer is completed, it should be enough to map /lib/firmware into the container to resolve the issue. 
 
 Is their any easy way I can change /lib/firmware to RW on my existing cluster, so I can test this fully?

**Comment by ibrokethecloud** [comment]
for existing 1.3.x users we may advise your workaround via a sytemd unit. 

I will get a new chart out today which maps /lib/firmware into the daemonset

**Comment by samueldewever** [comment]
> for existing 1.3.x users we may advise your workaround via a sytemd unit.
> 
> I will get a new chart out today which maps /lib/firmware into the daemonset

Perfect. In the meantime I have already changed the daemonset to map /lib/firmware in the pod and can confirm that this works. Once the new daemonset is available, I will double check and confirm that this one is OK.

**Comment by ibrokethecloud** [comment]
The new chart 0.4.1 released contains the additional mounts to mount `/lib/firmware`

This will go with 1.4.0 release as the `/lib/firmware` overlay has been added in v1.4.0


```spec:
  chart: nvidia-driver-runtime
  enabled: true
  repo: https://charts.harvesterhci.io
  valuesContent: >
    image:
      tag: v1.4-20241001
      repo: rancher/harvester-nvidia-driver-toolkit
    driverLocation:  "httpendpoint_to_driver"
    fullnameOverride: nvidia-driver-runtime
  version: 0.4.1
```

**Comment by samueldewever** [comment]
> The new chart 0.4.1 released contains the additional mounts to mount `/lib/firmware`
> 
> This will go with 1.4.0 release as the `/lib/firmware` overlay has been added in v1.4.0
> 
> ```
>   chart: nvidia-driver-runtime
>   enabled: true
>   repo: https://charts.harvesterhci.io
>   valuesContent: >
>     image:
>       tag: v1.4-20241001
>       repo: rancher/harvester-nvidia-driver-toolkit
>     driverLocation:  "httpendpoint_to_driver"
>     fullnameOverride: nvidia-driver-runtime
>   version: 0.4.1
> ```

@ibrokethecloud : I have tested the new chart and can confirm it works. 
One remark: the pod was failing, it took me a while to find out that it couldn't rmmod the nvidia modules because there were VMs running on the host. So the new pod could only start after I have shut all VMs on the host and than manually disabled the nvidia kernel modules. 

Might be a future enhancement to consider automating this in the nvidia driver toolkit installer.

**Comment by samueldewever** [comment]
We will check this week with the release 1.4.0 to double check thats it fixed.

**Comment by samueldewever** [comment]
@ibrokethecloud We tested 1.4.0 and everything is working now as expected.
Closing this issue now. Thank you.
